# Copyright (c) 2026 Raymond Manaloto
"""Tests for codex_schema module."""

from __future__ import annotations

import json
import pathlib
import subprocess
from types import SimpleNamespace
from typing import TYPE_CHECKING
from unittest.mock import patch

import pytest
from dotfiles_setup import codex_schema

if TYPE_CHECKING:
    from pathlib import Path


class TestSchemaPath:
    """Test schema_path resolution."""

    def test_schema_path_resolves_correctly(self, tmp_path: Path) -> None:
        """Schema path should resolve correctly."""
        result = codex_schema.schema_path(tmp_path)
        expected = tmp_path / "schemas" / "codex_app_server_protocol.schemas.json"
        assert result == expected


class TestVersionStamp:
    """Test the sidecar that binds generated bytes to a codex version."""

    def test_stamp_path_and_read_stamp_have_present_and_absent_arms(
        self, tmp_path: Path
    ) -> None:
        """The stamp reader must distinguish a recorded version from absence."""
        path = codex_schema.stamp_path(tmp_path)
        assert path == tmp_path / "schemas" / codex_schema.VERSION_STAMP_FILENAME
        path.parent.mkdir()
        path.write_text("0.154.0\n")
        assert codex_schema.read_stamp(tmp_path) == "0.154.0"

        path.unlink()
        assert codex_schema.read_stamp(tmp_path) is None


class TestValidateSchemaExists:
    """Test schema existence check."""

    def test_validate_schema_exists_returns_false_when_missing(
        self, tmp_path: Path
    ) -> None:
        """Should return False when schema file does not exist."""
        assert not codex_schema.validate_schema_exists(tmp_path)

    def test_validate_schema_exists_returns_true_when_present(
        self, tmp_path: Path
    ) -> None:
        """Should return True when schema file exists."""
        schema_dir = tmp_path / "schemas"
        schema_dir.mkdir()
        schema_file = schema_dir / "codex_app_server_protocol.schemas.json"
        schema_file.write_text("{}")

        assert codex_schema.validate_schema_exists(tmp_path)


class TestLoadSchema:
    """Test schema loading."""

    def test_load_schema_returns_none_when_missing(self, tmp_path: Path) -> None:
        """Should return None when schema file does not exist."""
        assert codex_schema.load_schema(tmp_path) is None

    def test_load_schema_returns_dict_when_present(self, tmp_path: Path) -> None:
        """Should parse and return schema as dict."""
        schema_dir = tmp_path / "schemas"
        schema_dir.mkdir()
        schema_file = schema_dir / "codex_app_server_protocol.schemas.json"
        test_schema = {"version": "0.154.0", "properties": {}}
        schema_file.write_text(json.dumps(test_schema))

        loaded = codex_schema.load_schema(tmp_path)
        assert loaded == test_schema
        assert loaded is not None
        assert loaded["version"] == "0.154.0"


class TestCheckSchemaCurrency:
    """Test schema currency validation."""

    def test_check_schema_currency_returns_false_when_missing(
        self, tmp_path: Path
    ) -> None:
        """Should return False when schema does not exist."""
        is_current, msg = codex_schema.check_schema_currency(tmp_path, "0.154.0")
        assert not is_current
        assert "not found" in msg.lower()

    def test_check_schema_currency_returns_true_when_present(
        self, tmp_path: Path
    ) -> None:
        """Should return True when schema and version sidecar agree."""
        schema_dir = tmp_path / "schemas"
        schema_dir.mkdir()
        schema_file = schema_dir / "codex_app_server_protocol.schemas.json"
        test_schema = {"type": "object"}
        schema_file.write_text(json.dumps(test_schema))
        codex_schema.stamp_path(tmp_path).write_text("0.154.0\n")

        is_current, msg = codex_schema.check_schema_currency(tmp_path, "0.154.0")
        assert is_current
        assert "0.154.0" in msg

    def test_check_schema_currency_rejects_absent_and_stale_stamps(
        self, tmp_path: Path
    ) -> None:
        """A bundle alone proves no version; a mismatched stamp proves staleness."""
        schema_dir = tmp_path / "schemas"
        schema_dir.mkdir()
        (schema_dir / "codex_app_server_protocol.schemas.json").write_text(
            json.dumps({"type": "object"})
        )

        is_current, msg = codex_schema.check_schema_currency(tmp_path, "0.154.0")
        assert not is_current
        assert "stamp not found" in msg.lower()

        codex_schema.stamp_path(tmp_path).write_text("0.0.0\n")
        is_current, msg = codex_schema.check_schema_currency(tmp_path, "0.154.0")
        assert not is_current
        assert "0.0.0" in msg
        assert "0.154.0" in msg

    def test_check_schema_currency_returns_false_for_invalid_json(
        self, tmp_path: Path
    ) -> None:
        """Should return False when schema contains invalid JSON."""
        schema_dir = tmp_path / "schemas"
        schema_dir.mkdir()
        schema_file = schema_dir / "codex_app_server_protocol.schemas.json"
        schema_file.write_text("{ invalid json")

        is_current, msg = codex_schema.check_schema_currency(tmp_path, "0.154.0")
        assert not is_current
        assert "invalid json" in msg.lower()


class TestGenerateSchema:
    """Test schema generation."""

    def test_generate_schema_creates_output_directory(self, tmp_path: Path) -> None:
        """Should create output directory if it does not exist."""
        output_dir = tmp_path / "schemas"
        assert not output_dir.exists()

        with patch("subprocess.run") as mock_run:
            mock_run.return_value.returncode = 0
            codex_schema.generate_schema(tmp_path, output_dir)

            assert output_dir.exists()

    def test_generate_schema_returns_true_only_when_the_bundle_lands(
        self, tmp_path: Path
    ) -> None:
        """rc=0 is not success — the bundle must actually arrive in output_dir.

        The generator writes to a staging dir and only the bundle is copied out.
        A subprocess that exits 0 while producing no bundle is a FAILURE, and
        returning True there would leave doctor asserting against a file that
        was never written. Both arms are checked here, which is the point: the
        happy arm alone would pass even if the copy step were deleted.
        """
        output_dir = tmp_path / "schemas"
        bundle = "codex_app_server_protocol.schemas.json"
        codex_schema.config_schema_path(tmp_path).parent.mkdir(parents=True)
        codex_schema.config_schema_path(tmp_path).write_text(
            json.dumps(
                {
                    "type": "object",
                    "additionalProperties": False,
                    "properties": {"developer_instructions": {"type": "string"}},
                    "definitions": {},
                }
            )
        )

        def _writes_the_bundle(
            cmd: list[str], *_a: object, **_k: object
        ) -> SimpleNamespace:
            if "--version" in cmd:
                return SimpleNamespace(
                    returncode=0, stdout="codex-cli 0.154.0\n", stderr=""
                )
            staging = pathlib.Path(cmd[cmd.index("--out") + 1])
            staging.mkdir(parents=True, exist_ok=True)
            (staging / bundle).write_text('{"generated": true}')
            return SimpleNamespace(returncode=0, stdout="", stderr="")

        with patch("subprocess.run", side_effect=_writes_the_bundle):
            assert codex_schema.generate_schema(tmp_path, output_dir) is True
        assert (output_dir / bundle).is_file(), "the bundle must be copied out"
        assert not list(output_dir.glob("*Params.json")), (
            "only bundles may be copied — per-message schemas stay in staging"
        )

        # FAIL ARM: rc=0 but the generator produced nothing.
        empty_out = tmp_path / "schemas_empty"
        with patch("subprocess.run") as mock_run:
            mock_run.return_value.returncode = 0
            assert codex_schema.generate_schema(tmp_path, empty_out) is False, (
                "rc=0 with no bundle produced must NOT report success"
            )

    def test_generate_schema_writes_agent_schema_and_version_stamp(
        self, tmp_path: Path
    ) -> None:
        """Generation must create both derived outputs and fail without its source."""
        output_dir = tmp_path / "schemas"
        output_dir.mkdir()
        config_schema = {
            "$schema": "http://json-schema.org/draft-07/schema#",
            "type": "object",
            "additionalProperties": False,
            "properties": {"developer_instructions": {"type": "string"}},
            "definitions": {},
        }
        codex_schema.config_schema_path(tmp_path).write_text(json.dumps(config_schema))

        def _successful_codex(
            cmd: list[str], *_a: object, **_k: object
        ) -> SimpleNamespace:
            if "--version" in cmd:
                return SimpleNamespace(
                    returncode=0, stdout="codex-cli 0.154.0\n", stderr=""
                )
            staging = pathlib.Path(cmd[cmd.index("--out") + 1])
            staging.mkdir(parents=True, exist_ok=True)
            (staging / "codex_app_server_protocol.schemas.json").write_text("{}")
            return SimpleNamespace(returncode=0, stdout="", stderr="")

        with patch("subprocess.run", side_effect=_successful_codex):
            assert codex_schema.generate_schema(tmp_path, output_dir)

        generated = json.loads((output_dir / "codex-agent.json").read_text())
        assert generated == codex_schema.derive_agent_schema(config_schema)
        assert (output_dir / codex_schema.VERSION_STAMP_FILENAME).read_text() == (
            "0.154.0\n"
        )

        # FAIL ARM: deleting the source schema must make generation fail closed.
        missing_source_root = tmp_path / "missing-source"
        with patch("subprocess.run", side_effect=_successful_codex):
            assert not codex_schema.generate_schema(
                missing_source_root, missing_source_root / "schemas"
            )

    def test_generate_schema_returns_false_on_failure(self, tmp_path: Path) -> None:
        """Should return False when codex app-server command fails."""
        output_dir = tmp_path / "schemas"

        with patch("subprocess.run") as mock_run:
            mock_run.return_value.returncode = 1
            result = codex_schema.generate_schema(tmp_path, output_dir)

            assert result is False

    def test_generate_schema_calls_correct_command(self, tmp_path: Path) -> None:
        """Should invoke correct codex command."""
        output_dir = tmp_path / "schemas"

        with patch("subprocess.run") as mock_run:
            mock_run.return_value.returncode = 0
            codex_schema.generate_schema(tmp_path, output_dir)

            # Verify the command was called correctly
            call_args = mock_run.call_args[0][0]
            assert "mise" in call_args
            assert "codex" in call_args
            assert "app-server" in call_args
            assert "generate-json-schema" in call_args

            # `--out` must NOT be the curated schemas/ directory. The generator
            # emits the whole protocol surface — measured 305 files, including
            # per-message schemas and v1/v2 subtrees — and only the bundle is
            # kept. Pointing it straight at schemas/ is what dumped 303
            # redundant files into a reviewed vendoring directory.
            out_target = call_args[call_args.index("--out") + 1]
            assert out_target != str(output_dir), (
                "generation must stage in a temp dir, not write schemas/ directly"
            )
            assert "codex-schema-" in out_target, (
                f"expected a codex-schema-* staging dir, got {out_target!r}"
            )


class TestGetInstalledCodexVersion:
    """Test codex version detection."""

    def test_get_installed_codex_version_parses_correctly(self) -> None:
        """Should parse version from 'codex-cli X.Y.Z' output."""
        with patch("subprocess.run") as mock_run:
            mock_run.return_value.stdout = "codex-cli 0.154.0\n"
            mock_run.return_value.returncode = 0
            version = codex_schema.get_installed_codex_version()

            assert version == "0.154.0"

    def test_get_installed_codex_version_raises_on_failure(self) -> None:
        """Should raise CalledProcessError when codex command fails."""
        with patch("subprocess.run") as mock_run:
            mock_run.side_effect = subprocess.CalledProcessError(1, "codex")
            with pytest.raises(subprocess.CalledProcessError):
                codex_schema.get_installed_codex_version()


class TestAgentSchemaDerivation:
    """The agent schema is DERIVED; it must not drift from its source."""

    def test_committed_agent_schema_matches_the_derivation(self) -> None:
        """`schemas/codex-agent.json` must equal derive(codex-config.json).

        It is generated, so a hand-edit or a stale copy after a codex bump is
        the failure this catches. The fail arm is below: a mutated property must
        make this test red, or the comparison is decoration.
        """
        root = pathlib.Path(__file__).parent.parent
        cfg = json.loads(codex_schema.config_schema_path(root).read_text())
        committed = json.loads(codex_schema.agent_schema_path(root).read_text())
        assert committed == codex_schema.derive_agent_schema(cfg), (
            "run `mise run codex-schema-generate` — the agent schema is stale"
        )

    def test_derivation_allows_the_agent_only_keys_and_requires_all_three(
        self,
    ) -> None:
        """`name`/`description` are agent-only; the config schema lacks them.

        Pointing an agent file at the RAW config schema rejects two of its three
        required keys — measured, all six specialists went INVALID that way. This
        pins the reason the derived schema exists.
        """
        cfg = {"properties": {"developer_instructions": {"type": "string"}}}
        for key in codex_schema.AGENT_ONLY_KEYS:
            assert key not in cfg["properties"], (
                f"{key} must NOT be a config.toml key — that is the whole point"
            )
        derived = codex_schema.derive_agent_schema(cfg)
        assert set(derived["required"]) == {
            "name",
            "description",
            "developer_instructions",
        }
        for key in codex_schema.AGENT_ONLY_KEYS:
            assert key in derived["properties"]
        assert derived["additionalProperties"] is False, (
            "a permissive agent schema cannot catch a wrong-typed key, which is "
            "the silent-drop failure it exists to prevent"
        )

    def test_derivation_preserves_mcp_servers_as_an_object(self) -> None:
        """The one type that mattered: `mcp_servers` must stay an OBJECT.

        `mcp_servers = ["context7"]` made every agent file invalid and codex
        dropped them silently. If the derivation ever loosened this, the schema
        would stop catching the exact defect that motivated it.
        """
        root = pathlib.Path(__file__).parent.parent
        derived = json.loads(codex_schema.agent_schema_path(root).read_text())
        assert derived["properties"]["mcp_servers"]["type"] == "object"
