# Copyright (c) 2026 Raymond Manaloto
"""Tests for `promote`'s pre-retag staleness guard (image_promote, #1007).

`promote` retags a PR's `:pr-N` image as `:dev`/`:latest` after verifying the
retag itself was faithful, but never asked whether the SOURCE was current —
measured 2026-09-11: `:dev` carried pre-#1004 bytes for ~3h45m while `:pr-1004`
already had the fix. This module proves eligibility from the registry alone,
by comparing the candidate against the smoke-validated `:dev-<dev-hash>`
marker CI already pushes.

Layers, mirroring `test_image_manifest.py`'s structure for the sibling AC2
guard:

1. **Six control arms**, using the REAL `compute_repo_dev_hash` against a
   mutated repo fixture (only the registry read is faked) — stale, fresh,
   shape-agnostic, multi-arch, missing-marker, and a hard registry failure
   that must never be reinterpreted as either of the other two verdicts
   (`.claude/rules/probes-need-a-control-arm.md` rule 9).
2. **Wiring** — the CLI subcommand really reaches the verifier, and the
   parsed `ci.yml` proves the guard step runs BEFORE the retag step and that
   the retag step's `if:` actually depends on it — a perfect but unreachable
   verifier is exactly the failure mode this prevents.
"""

from __future__ import annotations

import json
import subprocess
import sys
import textwrap
from pathlib import Path
from typing import TYPE_CHECKING

import pytest
import yaml

if TYPE_CHECKING:
    from collections.abc import Callable, Mapping

sys.path.insert(0, str(Path(__file__).parent.parent / "python" / "src"))

from dotfiles_setup.image_manifest import Inspector
from dotfiles_setup.image_promote import check_promote_eligibility, marker_ref
from dotfiles_setup.main import handle_image, setup_parser
from dotfiles_setup.p2996_hash import (
    BASE_SECTION_BEGIN,
    BASE_SECTION_END,
    P2996_SECTION_BEGIN,
    P2996_SECTION_END,
    compute_repo_dev_hash,
)
from dotfiles_setup.platform_target import published_targets

REPO_ROOT = Path(__file__).parent.parent

IMAGE = "ghcr.io/ray-manaloto/dotfiles-devcontainer"
CANDIDATE_REF = f"{IMAGE}:pr-1005"

#: `published_targets()` is amd64-then-arm64 (`PUBLISHED_ARCHES`) — reused
#: directly rather than hand-rolled `PublishTarget`s, so these tests exercise
#: the SAME platform strings (`linux/amd64/v2`, `linux/arm64/v8`) the real
#: CLI resolves through `check_promote_eligibility`'s `targets=None` default.
AMD64_TARGET, ARM64_TARGET = published_targets()

AMD64_STALE_DIGEST = "sha256:" + "a" * 64
AMD64_FRESH_DIGEST = "sha256:" + "b" * 64
ARM64_STALE_DIGEST = "sha256:" + "c" * 64
ARM64_FRESH_DIGEST = "sha256:" + "d" * 64


def _seed_repo(tmp_path: Path) -> Path:
    """A minimal repo tree `compute_repo_dev_hash` can read, no git needed.

    Copies `test_p2996_hash.py`'s `_seed_repo` fixture shape (same sentinel
    markers, same bake variables) — this file does not import that one
    since no test module here imports across test files, but the two must
    stay readable by the same hashing code, so the shape is deliberately
    identical.
    """
    (tmp_path / "docker-bake.hcl").write_text(
        'variable "BASE_IMAGE" { default = "ubuntu:26.04" }\n'
        'variable "PLATFORM" { default = "linux/amd64/v2" }\n'
        'variable "BUILDER_IMAGE" { default = "ubuntu:26.04@sha256:feedface" }\n'
        'variable "CLANG_P2996_REF" { default = "abc123" }\n'
        'target "dev" {\n'
        '  target = "devcontainer"\n'
        "  args = {\n"
        '    DEVCONTAINER_USER = "devcontainer"\n'
        "  }\n"
        "}\n",
    )
    devcontainer = tmp_path / ".devcontainer"
    devcontainer.mkdir()
    (devcontainer / "Dockerfile").write_text(
        textwrap.dedent(f"""\
        FROM ubuntu:26.04
        {BASE_SECTION_BEGIN}
        RUN apt-get update
        {BASE_SECTION_END}

        {P2996_SECTION_BEGIN}
        RUN cmake --build .
        {P2996_SECTION_END}

        FROM devcontainer-base AS devcontainer
        RUN echo final-stage
        """)
    )
    (devcontainer / "mise-system.lock").write_text(
        "# @generated by `mise lock`\n"
        '[[tools."conda:cmake"]]\nversion = "4.3.2"\nbackend = "conda:cmake"\n',
    )
    (devcontainer / "mise-system.toml").write_text(
        '[tools]\n"conda:cmake" = "latest"\n\n[settings]\nexperimental = true\n',
    )
    (tmp_path / "hk-common.pkl").write_text("hygiene = new {}\n")
    (tmp_path / "hk-image.pkl").write_text('amends "Config.pkl"\n')
    (devcontainer / "mise-runtime.toml").write_text('[tools]\nbats = "latest"\n')
    (devcontainer / "mise-runtime.lock").write_text(
        '[[tools.bats]]\nversion = "1.12.0"\n'
    )
    shared_dir = tmp_path / ".config" / "mise" / "conf.d"
    shared_dir.mkdir(parents=True)
    (shared_dir / "shared.toml").write_text('[tools]\nhk = "1.46.0"\n')
    return tmp_path


def _set_shared_toml(repo: Path, content: str) -> None:
    (repo / ".config" / "mise" / "conf.d" / "shared.toml").write_text(content)


@pytest.fixture
def repo(tmp_path: Path) -> Path:
    return _seed_repo(tmp_path)


def _index(*entries: dict[str, object]) -> str:
    return json.dumps(
        {
            "mediaType": "application/vnd.oci.image.index.v1+json",
            "manifests": list(entries),
        }
    )


def _entry(digest: str, arch: str, *, os_name: str = "linux") -> dict[str, object]:
    return {"digest": digest, "platform": {"architecture": arch, "os": os_name}}


def _inspector(
    raw: Mapping[str, str | BaseException],
    *,
    image_config: Mapping[str, str] | None = None,
    manifest_digest: Mapping[str, str] | None = None,
) -> Inspector:
    """A fake registry.

    Only `.raw` is populated unless a test needs the bare-manifest path —
    matching `test_image_manifest.py`'s `_inspector`.
    """

    def _raw(ref: str) -> str:
        value = raw[ref]
        if isinstance(value, BaseException):
            raise value
        return value

    def _missing(kind: str) -> Callable[[str], str]:
        def _raise(ref: str) -> str:
            msg = f"the promote guard consulted {kind} for {ref}; it must not"
            raise AssertionError(msg)

        return _raise

    return Inspector(
        raw=_raw,
        image_config=(
            (lambda ref: image_config[ref])
            if image_config is not None
            else _missing("{{json .Image}}")
        ),
        manifest_digest=(
            (lambda ref: manifest_digest[ref])
            if manifest_digest is not None
            else _missing("{{.Manifest.Digest}}")
        ),
    )


# ---------------------------------------------------------------------------
# Six control arms (spec §5)
# ---------------------------------------------------------------------------


def test_stale_candidate_is_rejected(repo: Path) -> None:
    """A candidate built before a later commit's marker must never retag."""
    _set_shared_toml(repo, '[tools]\ncodex = "0.152.1"\n')
    stale_hash = compute_repo_dev_hash(repo, platform=AMD64_TARGET.platform)

    _set_shared_toml(repo, '[tools]\ncodex = "0.154.0"\nminimum_release_age = "0s"\n')
    fresh_hash = compute_repo_dev_hash(repo, platform=AMD64_TARGET.platform)
    assert fresh_hash != stale_hash, "the fixture must genuinely differ"

    fresh_marker = marker_ref(IMAGE, fresh_hash)
    raw: dict[str, str | BaseException] = {
        CANDIDATE_REF: _index(_entry(AMD64_STALE_DIGEST, "amd64")),
        fresh_marker: _index(_entry(AMD64_FRESH_DIGEST, "amd64")),
    }
    verdict = check_promote_eligibility(
        repo_root=repo,
        candidate_ref=CANDIDATE_REF,
        inspector=_inspector(raw),
        targets=(AMD64_TARGET,),
    )
    assert not verdict.eligible
    assert verdict.status == "stale"
    line = verdict.lines[0]
    assert "amd64" in line
    assert CANDIDATE_REF in line
    assert AMD64_STALE_DIGEST in line
    assert fresh_marker in line
    assert AMD64_FRESH_DIGEST in line
    assert fresh_hash in line


def test_fresh_candidate_is_eligible(repo: Path) -> None:
    """Passing control: change ONLY the candidate entry to the fresh digest."""
    fresh_hash = compute_repo_dev_hash(repo, platform=AMD64_TARGET.platform)
    fresh_marker = marker_ref(IMAGE, fresh_hash)
    raw = {
        CANDIDATE_REF: _index(_entry(AMD64_FRESH_DIGEST, "amd64")),
        fresh_marker: _index(_entry(AMD64_FRESH_DIGEST, "amd64")),
    }
    verdict = check_promote_eligibility(
        repo_root=repo,
        candidate_ref=CANDIDATE_REF,
        inspector=_inspector(raw),
        targets=(AMD64_TARGET,),
    )
    assert verdict.eligible
    assert verdict.status == "eligible"


def test_bare_manifest_marker_still_resolves(repo: Path) -> None:
    """Shape control: the fresh marker is a bare manifest, not an index."""
    fresh_hash = compute_repo_dev_hash(repo, platform=AMD64_TARGET.platform)
    fresh_marker = marker_ref(IMAGE, fresh_hash)
    bare_manifest = json.dumps(
        {
            "mediaType": "application/vnd.oci.image.manifest.v1+json",
            "config": {"digest": "sha256:" + "e" * 64},
            "layers": [],
        }
    )
    raw = {
        CANDIDATE_REF: _index(_entry(AMD64_FRESH_DIGEST, "amd64")),
        fresh_marker: bare_manifest,
    }
    verdict = check_promote_eligibility(
        repo_root=repo,
        candidate_ref=CANDIDATE_REF,
        inspector=_inspector(
            raw,
            image_config={
                fresh_marker: json.dumps({"architecture": "amd64", "os": "linux"})
            },
            manifest_digest={fresh_marker: AMD64_FRESH_DIGEST},
        ),
        targets=(AMD64_TARGET,),
    )
    assert verdict.eligible


def test_multi_arch_one_stale_arch_rejects_the_whole_candidate(repo: Path) -> None:
    """amd64 matches, arm64 is stale — the WHOLE candidate must be rejected."""
    amd64_fresh_hash = compute_repo_dev_hash(repo, platform=AMD64_TARGET.platform)
    arm64_fresh_hash = compute_repo_dev_hash(repo, platform=ARM64_TARGET.platform)
    assert amd64_fresh_hash != arm64_fresh_hash, "platform must move the hash"

    amd64_marker = marker_ref(IMAGE, amd64_fresh_hash)
    arm64_marker = marker_ref(IMAGE, arm64_fresh_hash)
    raw = {
        CANDIDATE_REF: _index(
            _entry(AMD64_FRESH_DIGEST, "amd64"),
            # arm64 candidate does NOT match its own marker below.
            _entry(ARM64_STALE_DIGEST, "arm64"),
        ),
        amd64_marker: _index(_entry(AMD64_FRESH_DIGEST, "amd64")),
        arm64_marker: _index(_entry(ARM64_FRESH_DIGEST, "arm64")),
    }
    verdict = check_promote_eligibility(
        repo_root=repo,
        candidate_ref=CANDIDATE_REF,
        inspector=_inspector(raw),
        targets=(AMD64_TARGET, ARM64_TARGET),
    )
    assert not verdict.eligible
    assert verdict.status == "stale"
    assert any("arm64" in line for line in verdict.lines)


def test_missing_marker_is_unprovable_never_current(repo: Path) -> None:
    """An absent marker must classify as UNPROVABLE, never as eligible."""
    fresh_hash = compute_repo_dev_hash(repo, platform=AMD64_TARGET.platform)
    fresh_marker = marker_ref(IMAGE, fresh_hash)
    raw: dict[str, str | BaseException] = {
        CANDIDATE_REF: _index(_entry(AMD64_FRESH_DIGEST, "amd64")),
        fresh_marker: subprocess.CalledProcessError(
            1, ["docker", "buildx", "imagetools", "inspect"], stderr="manifest unknown"
        ),
    }
    verdict = check_promote_eligibility(
        repo_root=repo,
        candidate_ref=CANDIDATE_REF,
        inspector=_inspector(raw),
        targets=(AMD64_TARGET,),
    )
    assert not verdict.eligible
    assert verdict.status == "unprovable"
    assert fresh_marker in verdict.lines[0]


def test_registry_auth_failure_is_a_hard_failure_not_a_verdict(repo: Path) -> None:
    """An auth/network error must propagate — never read as stale or missing."""
    fresh_hash = compute_repo_dev_hash(repo, platform=AMD64_TARGET.platform)
    fresh_marker = marker_ref(IMAGE, fresh_hash)
    raw: dict[str, str | BaseException] = {
        CANDIDATE_REF: _index(_entry(AMD64_FRESH_DIGEST, "amd64")),
        fresh_marker: subprocess.CalledProcessError(
            1,
            ["docker", "buildx", "imagetools", "inspect"],
            stderr="unauthorized: authentication required",
        ),
    }
    with pytest.raises(subprocess.CalledProcessError):
        check_promote_eligibility(
            repo_root=repo,
            candidate_ref=CANDIDATE_REF,
            inspector=_inspector(raw),
            targets=(AMD64_TARGET,),
        )


# ---------------------------------------------------------------------------
# Wiring — a perfect but unreachable verifier is the failure this prevents
# ---------------------------------------------------------------------------


def test_cli_parses_and_routes_verify_promote_eligibility() -> None:
    parser = setup_parser()
    args = parser.parse_args(
        ["image", "verify-promote-eligibility", "--image-ref", CANDIDATE_REF]
    )
    assert args.image_command == "verify-promote-eligibility"
    assert args.image_ref == CANDIDATE_REF


def test_public_cli_executes_the_verifier(
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
    repo: Path,
) -> None:
    """Both CLI dispatch layers really reach `check_promote_eligibility`.

    Exercises the CLI's real default (`targets=None` -> `published_targets()`
    -> BOTH architectures), so this is the one test that is not narrowed to a
    single `targets=` override.
    """
    monkeypatch.setattr("dotfiles_setup.image._project_root", lambda: repo)
    amd64_hash = compute_repo_dev_hash(repo, platform=AMD64_TARGET.platform)
    arm64_hash = compute_repo_dev_hash(repo, platform=ARM64_TARGET.platform)
    amd64_marker = marker_ref(IMAGE, amd64_hash)
    arm64_marker = marker_ref(IMAGE, arm64_hash)
    raw = {
        CANDIDATE_REF: _index(
            _entry(AMD64_FRESH_DIGEST, "amd64"), _entry(ARM64_FRESH_DIGEST, "arm64")
        ),
        amd64_marker: _index(_entry(AMD64_FRESH_DIGEST, "amd64")),
        arm64_marker: _index(_entry(ARM64_FRESH_DIGEST, "arm64")),
    }
    monkeypatch.setattr(
        "dotfiles_setup.image.docker_inspector", lambda: _inspector(raw)
    )
    args = setup_parser().parse_args(
        ["image", "verify-promote-eligibility", "--image-ref", CANDIDATE_REF]
    )

    with pytest.raises(SystemExit) as exit_info:
        handle_image(args)

    assert exit_info.value.code == 0
    out = capsys.readouterr().out
    assert "eligible=true" in out
    assert "status=eligible" in out


def _promote_steps() -> list[dict]:
    workflow = yaml.safe_load((REPO_ROOT / ".github/workflows/ci.yml").read_text())
    return workflow["jobs"]["promote"]["steps"]


def test_eligibility_step_precedes_and_gates_the_retag_step() -> None:
    """A perfect verifier nobody calls, or a retag that ignores it, is a no-op."""
    steps = _promote_steps()
    names = [step.get("name", "") for step in steps]
    eligibility_index = next(
        i for i, name in enumerate(names) if "content-current" in name
    )
    retag_name = "Retag PR image as :dev and :latest"
    retag_index = next(i for i, name in enumerate(names) if name == retag_name)
    assert eligibility_index < retag_index, (
        "the staleness guard must run BEFORE the retag step"
    )

    eligibility_step = steps[eligibility_index]
    assert eligibility_step["id"] == "eligibility"
    assert "dotfiles-setup image verify-promote-eligibility" in eligibility_step["run"]

    retag_step = steps[retag_index]
    assert "steps.eligibility.outputs.eligible == 'true'" in retag_step["if"]
