"""Tests for `dotfiles_setup.p2996_hash`."""

from __future__ import annotations

import os
import re
import subprocess
import sys
import textwrap
from pathlib import Path

import pytest

from dotfiles_setup.p2996_hash import (
    BASE_SECTION_BEGIN,
    BASE_SECTION_END,
    HASH_LENGTH,
    P2996_SECTION_BEGIN,
    P2996_SECTION_END,
    BaseHashInputs,
    DevHashInputs,
    P2996HashInputs,
    _extract_bake_target_block,
    _extract_bake_variable,
    _extract_dockerfile_section,
    compute_base_hash,
    compute_dev_hash,
    compute_p2996_hash,
    compute_repo_base_hash,
    compute_repo_dev_hash,
    compute_repo_p2996_hash,
    gather_base_inputs,
    gather_dev_inputs,
    gather_p2996_inputs,
)


# ──────────────────────────────────────────────────────────────────────
# Stub helpers
# ──────────────────────────────────────────────────────────────────────


def _stub_base_inputs(**overrides: str) -> BaseHashInputs:
    base = {
        "base_image": "ubuntu:26.04",
        "platform": "linux/amd64/v2",
        "base_section_digest": "a" * 64,
        "mise_lock_digest": "c" * 64,
        "mise_system_config_digest": "f" * 64,
        "shared_config_digest": "9" * 64,
        "hk_config_digest": "b" * 64,
    }
    base.update(overrides)
    return BaseHashInputs(**base)


def _stub_p2996_inputs(**overrides: str) -> P2996HashInputs:
    base = {
        "clang_p2996_ref": "9ffb96e3ce362289008e14ad2a79a249f58aa90a",
        "builder_image": "ubuntu:26.04@sha256:feedfacefeedface",
        "platform": "linux/amd64/v2",
        "p2996_section_digest": "b" * 64,
    }
    base.update(overrides)
    return P2996HashInputs(**base)


def _stub_dev_inputs(**overrides: str) -> DevHashInputs:
    base = {
        "base_hash": "0123456789abcdef",
        "p2996_hash": "fedcba9876543210",
        "platform": "linux/amd64/v2",
        "dockerfile_digest": "d" * 64,
        "dev_target_digest": "e" * 64,
        "runtime_config_digest": "a" * 64,
        "runtime_lock_digest": "b" * 64,
    }
    base.update(overrides)
    return DevHashInputs(**base)


def _seed_repo(tmp_path: Path) -> Path:
    """Write a minimal repo tree with valid Dockerfile section markers.

    Includes a `dev` bake target (with nested `args` braces) and a
    final-stage Dockerfile line OUTSIDE the sentinels so the dev-hash
    tests can exercise whole-Dockerfile + dev-target hashing.
    """
    (tmp_path / "docker-bake.hcl").write_text(
        'variable "BASE_IMAGE" { default = "ubuntu:26.04" }\n'
        'variable "PLATFORM" { default = "linux/amd64/v2" }\n'
        'variable "BUILDER_IMAGE" { default = "ubuntu:26.04@sha256:feedface" }\n'
        'variable "CLANG_P2996_REF" { default = "abc123" }\n'
        'target "dev" {\n'
        '  target = "devcontainer"\n'
        "  args = {\n"
        '    DEVCONTAINER_USERNAME = "devcontainer"\n'
        "  }\n"
        "}\n",
    )
    devcontainer = tmp_path / ".devcontainer"
    devcontainer.mkdir()
    (devcontainer / "Dockerfile").write_text(
        textwrap.dedent(f"""\
        FROM ubuntu:26.04
        {BASE_SECTION_BEGIN}
        RUN apt-get update
        {BASE_SECTION_END}

        {P2996_SECTION_BEGIN}
        RUN cmake --build .
        {P2996_SECTION_END}

        FROM devcontainer-base AS devcontainer
        RUN echo final-stage
        """)
    )
    (devcontainer / "mise-system.lock").write_text(
        "# @generated by `mise lock`\n"
        '[[tools."conda:cmake"]]\nversion = "4.3.2"\nbackend = "conda:cmake"\n',
    )
    (devcontainer / "mise-system.toml").write_text(
        '[tools]\n"conda:cmake" = "latest"\n\n[settings]\nexperimental = true\n',
    )
    # hk-common.pkl + hk-image.pkl are base-section COPY inputs hashed into the
    # base hash (they land at /etc/hk/ in the image).
    (tmp_path / "hk-common.pkl").write_text("hygiene = new {}\n")
    (tmp_path / "hk-image.pkl").write_text('amends "Config.pkl"\n')
    # The runtime tier files are devcontainer-runtime COPY inputs hashed
    # into dev-hash (#160 T9/T10).
    (devcontainer / "mise-runtime.toml").write_text('[tools]\nbats = "latest"\n')
    (devcontainer / "mise-runtime.lock").write_text(
        '[[tools.bats]]\nversion = "1.12.0"\n'
    )
    # The shared conf.d fragment is a base-section COPY input too (#160 T5).
    shared_dir = tmp_path / ".config" / "mise" / "conf.d"
    shared_dir.mkdir(parents=True)
    (shared_dir / "shared.toml").write_text('[tools]\nhk = "1.46.0"\n')
    return tmp_path


# ──────────────────────────────────────────────────────────────────────
# BaseHashInputs validation
# ──────────────────────────────────────────────────────────────────────


def test_base_hash_is_stable_for_fixed_inputs() -> None:
    inputs = _stub_base_inputs()
    assert compute_base_hash(inputs) == compute_base_hash(inputs)
    assert len(compute_base_hash(inputs)) == HASH_LENGTH


def test_base_hash_is_lowercase_hex() -> None:
    digest = compute_base_hash(_stub_base_inputs())
    assert digest == digest.lower()
    assert all(c in "0123456789abcdef" for c in digest)


def test_base_hash_changes_when_base_image_changes() -> None:
    base = _stub_base_inputs()
    bumped = _stub_base_inputs(base_image="ubuntu:25.10")
    assert compute_base_hash(base) != compute_base_hash(bumped)


def test_base_hash_changes_when_section_digest_changes() -> None:
    base = _stub_base_inputs()
    bumped = _stub_base_inputs(base_section_digest="d" * 64)
    assert compute_base_hash(base) != compute_base_hash(bumped)


def test_base_hash_changes_when_mise_lock_digest_changes() -> None:
    # Epic #160: the base hash reads the native mise-system.lock digest
    # (rattler conda sha256 + version pins) in place of the retired
    # version-only snapshot — conda-forge drift moves the lock's checksums.
    base = _stub_base_inputs()
    bumped = _stub_base_inputs(mise_lock_digest="e" * 64)
    assert compute_base_hash(base) != compute_base_hash(bumped)


def test_base_hash_changes_when_shared_config_digest_changes() -> None:
    # Epic #160 T5: the shared conf.d fragment is COPYd into the image and
    # supplies 20 exact-pinned tools, so a version bump there must bust the
    # base hash and trigger a rebuild.
    base = _stub_base_inputs()
    bumped = _stub_base_inputs(shared_config_digest="7" * 64)
    assert compute_base_hash(base) != compute_base_hash(bumped)


def test_base_hash_changes_when_mise_system_config_digest_changes() -> None:
    # PR #140: mise-system.toml is COPYed into the image, so [settings]/
    # [env]/[tasks] edits that don't move the lock must still
    # bust the base hash and trigger a rebuild.
    base = _stub_base_inputs()
    bumped = _stub_base_inputs(mise_system_config_digest="e" * 64)
    assert compute_base_hash(base) != compute_base_hash(bumped)


def test_repo_base_hash_changes_when_mise_system_toml_edited(tmp_path: Path) -> None:
    _seed_repo(tmp_path)
    before = compute_repo_base_hash(tmp_path)
    toml = tmp_path / ".devcontainer" / "mise-system.toml"
    # A pure [settings] edit — does NOT touch mise-system.lock.
    toml.write_text(
        toml.read_text().replace("experimental = true", "asdf_compat = true")
    )
    after = compute_repo_base_hash(tmp_path)
    assert before != after


def test_base_hash_changes_when_hk_config_digest_changes() -> None:
    # The base section COPYs hk-common.pkl + hk-image.pkl to /etc/hk/; their
    # bytes must bust the base hash (previously unhashed — #154's builtin wiring
    # edit did not trigger a rebuild, leaving a stale in-image hk config).
    base = _stub_base_inputs()
    bumped = _stub_base_inputs(hk_config_digest="d" * 64)
    assert compute_base_hash(base) != compute_base_hash(bumped)


def test_repo_base_hash_changes_when_hk_image_pkl_edited(tmp_path: Path) -> None:
    _seed_repo(tmp_path)
    before = compute_repo_base_hash(tmp_path)
    hk_image = tmp_path / "hk-image.pkl"
    hk_image.write_text(hk_image.read_text() + '\nimport "Builtins.pkl"\n')
    after = compute_repo_base_hash(tmp_path)
    assert before != after


def test_repo_base_hash_changes_when_hk_common_pkl_edited(tmp_path: Path) -> None:
    _seed_repo(tmp_path)
    before = compute_repo_base_hash(tmp_path)
    hk_common = tmp_path / "hk-common.pkl"
    hk_common.write_text(hk_common.read_text() + "\nsafety = new {}\n")
    after = compute_repo_base_hash(tmp_path)
    assert before != after


def test_base_inputs_reject_empty_literal() -> None:
    with pytest.raises(ValueError, match="must be non-empty"):
        _stub_base_inputs(base_image="")


def test_base_inputs_reject_short_digest() -> None:
    with pytest.raises(ValueError, match="64-char"):
        _stub_base_inputs(base_section_digest="a" * 63)


def test_base_inputs_reject_uppercase_digest() -> None:
    with pytest.raises(ValueError, match="64-char"):
        _stub_base_inputs(mise_lock_digest="A" * 64)


# ──────────────────────────────────────────────────────────────────────
# P2996HashInputs validation
# ──────────────────────────────────────────────────────────────────────


def test_p2996_hash_is_stable_for_fixed_inputs() -> None:
    inputs = _stub_p2996_inputs()
    assert compute_p2996_hash(inputs) == compute_p2996_hash(inputs)
    assert len(compute_p2996_hash(inputs)) == HASH_LENGTH


def test_p2996_hash_changes_when_clang_ref_changes() -> None:
    base = _stub_p2996_inputs()
    bumped = _stub_p2996_inputs(clang_p2996_ref="0" * 40)
    assert compute_p2996_hash(base) != compute_p2996_hash(bumped)


def test_p2996_hash_changes_when_builder_image_changes() -> None:
    # T11: a BUILDER_IMAGE digest bump means different compiler inputs and
    # must move the hash (it replaced base_hash as the toolchain signal).
    base = _stub_p2996_inputs()
    bumped = _stub_p2996_inputs(builder_image="ubuntu:26.04@sha256:0badc0de")
    assert compute_p2996_hash(base) != compute_p2996_hash(bumped)


def test_p2996_hash_changes_when_platform_changes() -> None:
    base = _stub_p2996_inputs()
    bumped = _stub_p2996_inputs(platform="linux/arm64")
    assert compute_p2996_hash(base) != compute_p2996_hash(bumped)


def test_p2996_hash_changes_when_p2996_section_digest_changes() -> None:
    base = _stub_p2996_inputs()
    bumped = _stub_p2996_inputs(p2996_section_digest="d" * 64)
    assert compute_p2996_hash(base) != compute_p2996_hash(bumped)


def test_p2996_inputs_reject_empty_clang_ref() -> None:
    with pytest.raises(ValueError, match="must be non-empty"):
        _stub_p2996_inputs(clang_p2996_ref="")


def test_p2996_inputs_reject_empty_builder_image() -> None:
    with pytest.raises(ValueError, match="must be non-empty"):
        _stub_p2996_inputs(builder_image="")


# ──────────────────────────────────────────────────────────────────────
# Decoupling: editing one section does NOT invalidate the other hash
# ──────────────────────────────────────────────────────────────────────


def test_p2996_hash_moves_on_section_digest_alone() -> None:
    # With builder/platform/ref held constant, the p2996-section input is
    # the only thing that determines p2996-hash.
    a = _stub_p2996_inputs(p2996_section_digest="a" * 64)
    b = _stub_p2996_inputs(p2996_section_digest="b" * 64)
    assert compute_p2996_hash(a) != compute_p2996_hash(b)


def test_base_and_p2996_hashes_have_different_kind_namespacing() -> None:
    # Even with identical-looking inputs, base and p2996 hashes are
    # namespaced by `kind=base` vs `kind=p2996` in the canonical
    # string so a base hash can never collide with a p2996 hash.
    same_digest = "a" * 64
    base = compute_base_hash(
        _stub_base_inputs(base_section_digest=same_digest, mise_lock_digest=same_digest)
    )
    p2996 = compute_p2996_hash(_stub_p2996_inputs(p2996_section_digest=same_digest))
    assert base != p2996


# ──────────────────────────────────────────────────────────────────────
# Bake variable + dockerfile section parsers
# ──────────────────────────────────────────────────────────────────────


def test_extract_bake_variable_simple() -> None:
    bake = """
    variable "BASE_IMAGE" {
      default = "ubuntu:26.04"
    }
    """
    assert _extract_bake_variable(bake, "BASE_IMAGE") == "ubuntu:26.04"


def test_extract_bake_variable_missing_raises() -> None:
    bake = 'variable "OTHER" { default = "x" }'
    with pytest.raises(ValueError, match="not found"):
        _extract_bake_variable(bake, "MISSING_VAR")


def test_extract_dockerfile_section_returns_inclusive_slice() -> None:
    text = f"before\n{BASE_SECTION_BEGIN}\nRUN echo base\n{BASE_SECTION_END}\nafter\n"
    section = _extract_dockerfile_section(text, BASE_SECTION_BEGIN, BASE_SECTION_END)
    assert BASE_SECTION_BEGIN in section
    assert BASE_SECTION_END in section
    assert "RUN echo base" in section
    assert "before" not in section
    assert "after" not in section


def test_extract_dockerfile_section_missing_marker_raises() -> None:
    with pytest.raises(ValueError, match="not found"):
        _extract_dockerfile_section(
            "no markers here", BASE_SECTION_BEGIN, BASE_SECTION_END
        )


def test_extract_dockerfile_section_inverted_markers_raises() -> None:
    text = f"{BASE_SECTION_END}\n{BASE_SECTION_BEGIN}\n"
    with pytest.raises(ValueError, match="out of order"):
        _extract_dockerfile_section(text, BASE_SECTION_BEGIN, BASE_SECTION_END)


# ──────────────────────────────────────────────────────────────────────
# Repo-level hashing
# ──────────────────────────────────────────────────────────────────────


def test_gather_and_compute_repo_base_hash_roundtrip(tmp_path: Path) -> None:
    _seed_repo(tmp_path)
    inputs = gather_base_inputs(tmp_path)
    assert inputs.base_image == "ubuntu:26.04"
    assert inputs.platform == "linux/amd64/v2"
    digest_a = compute_repo_base_hash(tmp_path)
    digest_b = compute_repo_base_hash(tmp_path)
    assert digest_a == digest_b
    assert len(digest_a) == HASH_LENGTH


def test_repo_base_hash_changes_when_base_section_modified(tmp_path: Path) -> None:
    _seed_repo(tmp_path)
    before = compute_repo_base_hash(tmp_path)
    dockerfile = tmp_path / ".devcontainer" / "Dockerfile"
    dockerfile.write_text(
        dockerfile.read_text().replace("RUN apt-get update", "RUN apt-get install foo")
    )
    after = compute_repo_base_hash(tmp_path)
    assert before != after


def test_repo_base_hash_unchanged_when_p2996_section_modified(tmp_path: Path) -> None:
    # The whole point of the split: editing only the p2996 section of
    # the Dockerfile must NOT invalidate the base hash.
    _seed_repo(tmp_path)
    before = compute_repo_base_hash(tmp_path)
    dockerfile = tmp_path / ".devcontainer" / "Dockerfile"
    dockerfile.write_text(
        dockerfile.read_text().replace(
            "RUN cmake --build .", "RUN cmake --build . --verbose"
        )
    )
    after = compute_repo_base_hash(tmp_path)
    assert before == after


def test_repo_p2996_hash_changes_when_p2996_section_modified(tmp_path: Path) -> None:
    _seed_repo(tmp_path)
    before = compute_repo_p2996_hash(tmp_path)
    dockerfile = tmp_path / ".devcontainer" / "Dockerfile"
    dockerfile.write_text(
        dockerfile.read_text().replace(
            "RUN cmake --build .", "RUN cmake --build . --verbose"
        )
    )
    after = compute_repo_p2996_hash(tmp_path)
    assert before != after


def test_repo_p2996_hash_unchanged_when_base_section_modified(tmp_path: Path) -> None:
    # T11 PROOF TEST (inverted from the pre-decouple coupling assertion):
    # base-section edits move base-hash but must leave p2996-hash ALONE —
    # the builder no longer descends from devcontainer-base, so mise/hk/
    # base edits never trigger the ~2h compiler rebuild.
    _seed_repo(tmp_path)
    base_before = compute_repo_base_hash(tmp_path)
    p2996_before = compute_repo_p2996_hash(tmp_path)
    dockerfile = tmp_path / ".devcontainer" / "Dockerfile"
    dockerfile.write_text(
        dockerfile.read_text().replace("RUN apt-get update", "RUN apt-get install foo")
    )
    assert compute_repo_base_hash(tmp_path) != base_before
    assert compute_repo_p2996_hash(tmp_path) == p2996_before


def test_repo_p2996_hash_unchanged_when_mise_system_toml_edited(tmp_path: Path) -> None:
    _seed_repo(tmp_path)
    before = compute_repo_p2996_hash(tmp_path)
    path = tmp_path / ".devcontainer" / "mise-system.toml"
    path.write_text(path.read_text() + '"conda:extra" = "latest"\n')
    assert compute_repo_p2996_hash(tmp_path) == before


def test_repo_p2996_hash_unchanged_when_shared_toml_edited(tmp_path: Path) -> None:
    _seed_repo(tmp_path)
    before = compute_repo_p2996_hash(tmp_path)
    path = tmp_path / ".config" / "mise" / "conf.d" / "shared.toml"
    path.write_text(path.read_text() + 'jq = "1.8.1"\n')
    assert compute_repo_p2996_hash(tmp_path) == before


def test_repo_p2996_hash_unchanged_when_hk_common_pkl_edited(tmp_path: Path) -> None:
    _seed_repo(tmp_path)
    before = compute_repo_p2996_hash(tmp_path)
    path = tmp_path / "hk-common.pkl"
    path.write_text(path.read_text() + "extra = new {}\n")
    assert compute_repo_p2996_hash(tmp_path) == before


def test_repo_p2996_hash_unchanged_when_mise_lock_edited(tmp_path: Path) -> None:
    _seed_repo(tmp_path)
    before = compute_repo_p2996_hash(tmp_path)
    path = tmp_path / ".devcontainer" / "mise-system.lock"
    path.write_text(path.read_text() + "# drift\n")
    assert compute_repo_p2996_hash(tmp_path) == before


# ──────────────────────────────────────────────────────────────────────
# Phase D (#120): clang_p2996_ref override
# ──────────────────────────────────────────────────────────────────────


def test_gather_p2996_inputs_override_replaces_bake_pin(tmp_path: Path) -> None:
    _seed_repo(tmp_path)
    pinned = gather_p2996_inputs(tmp_path)
    assert pinned.clang_p2996_ref == "abc123"  # the seeded bake default
    overridden = gather_p2996_inputs(tmp_path, clang_p2996_ref="deadbeef")
    assert overridden.clang_p2996_ref == "deadbeef"


def test_gather_p2996_inputs_none_override_uses_pin(tmp_path: Path) -> None:
    # Explicit None must be byte-identical to omitting the arg — the
    # canonical-build invariant the empty dispatch input relies on.
    _seed_repo(tmp_path)
    assert gather_p2996_inputs(tmp_path, clang_p2996_ref=None) == gather_p2996_inputs(
        tmp_path
    )


def test_repo_p2996_hash_override_differs_from_pin(tmp_path: Path) -> None:
    _seed_repo(tmp_path)
    pinned = compute_repo_p2996_hash(tmp_path)
    overridden = compute_repo_p2996_hash(tmp_path, clang_p2996_ref="deadbeef")
    assert pinned != overridden


def test_repo_p2996_hash_override_equal_to_pin_matches(tmp_path: Path) -> None:
    # Overriding with the SAME value the bake file pins must reproduce the
    # canonical hash exactly — proves the override channel is pure.
    _seed_repo(tmp_path)
    assert compute_repo_p2996_hash(
        tmp_path, clang_p2996_ref="abc123"
    ) == compute_repo_p2996_hash(tmp_path)


def test_repo_dev_hash_override_differs_from_pin(tmp_path: Path) -> None:
    # The override must propagate through the nested p2996 hash into the
    # dev hash so the dev-tag validated marker tracks overridden content.
    _seed_repo(tmp_path)
    pinned = compute_repo_dev_hash(tmp_path)
    overridden = compute_repo_dev_hash(tmp_path, clang_p2996_ref="deadbeef")
    assert pinned != overridden


# ──────────────────────────────────────────────────────────────────────
# Failure modes
# ──────────────────────────────────────────────────────────────────────


def test_gather_base_inputs_missing_dockerfile_raises(tmp_path: Path) -> None:
    (tmp_path / "docker-bake.hcl").write_text(
        'variable "BASE_IMAGE" { default = "ubuntu:26.04" }\n'
        'variable "PLATFORM" { default = "linux/amd64/v2" }\n'
        'variable "BUILDER_IMAGE" { default = "ubuntu:26.04@sha256:feedface" }\n'
        'variable "CLANG_P2996_REF" { default = "abc" }\n',
    )
    (tmp_path / ".devcontainer").mkdir()
    (tmp_path / ".devcontainer" / "mise-system.lock").write_text("# empty\n")
    with pytest.raises(FileNotFoundError):
        gather_base_inputs(tmp_path)


def test_gather_p2996_inputs_missing_marker_raises(tmp_path: Path) -> None:
    _seed_repo(tmp_path)
    dockerfile = tmp_path / ".devcontainer" / "Dockerfile"
    # Strip the p2996 begin marker.
    dockerfile.write_text(dockerfile.read_text().replace(P2996_SECTION_BEGIN, ""))
    with pytest.raises(ValueError, match="not found"):
        gather_p2996_inputs(tmp_path)


# ──────────────────────────────────────────────────────────────────────
# CLI dispatch smoke tests (the CI shell pipelines depend on these)
# ──────────────────────────────────────────────────────────────────────


def _run_dotfiles_setup(subcommand: str, *, env_override: str | None = None) -> str:
    env = dict(os.environ)
    # Phase D (#120): the CLI reads CLANG_P2996_REF from the environment to
    # override the committed pin. None leaves the ambient env untouched.
    env.pop("CLANG_P2996_REF", None)
    if env_override is not None:
        env["CLANG_P2996_REF"] = env_override
    result = subprocess.run(
        [sys.executable, "-m", "dotfiles_setup.main", subcommand],
        capture_output=True,
        text=True,
        check=True,
        cwd=Path(__file__).resolve().parent.parent,
        env=env,
    )
    return result.stdout.strip()


def test_cli_p2996_hash_returns_16_char_hex() -> None:
    output = _run_dotfiles_setup("p2996-hash")
    assert len(output) == HASH_LENGTH, (
        f"expected {HASH_LENGTH}-char hex digest from CLI, got {output!r}"
    )
    assert re.fullmatch(r"[0-9a-f]+", output), (
        f"expected lowercase-hex digest from CLI, got {output!r}"
    )


def test_cli_base_hash_returns_16_char_hex() -> None:
    output = _run_dotfiles_setup("base-hash")
    assert len(output) == HASH_LENGTH
    assert re.fullmatch(r"[0-9a-f]+", output)


def test_cli_dev_hash_returns_16_char_hex() -> None:
    output = _run_dotfiles_setup("dev-hash")
    assert len(output) == HASH_LENGTH
    assert re.fullmatch(r"[0-9a-f]+", output)


def test_cli_p2996_hash_honors_clang_ref_env_override() -> None:
    # Phase D (#120): an exported CLANG_P2996_REF must change the emitted
    # p2996 hash so the dispatch path's cache tag tracks the overridden SHA.
    pinned = _run_dotfiles_setup("p2996-hash")
    overridden = _run_dotfiles_setup("p2996-hash", env_override="0" * 40)
    assert pinned != overridden
    assert len(overridden) == HASH_LENGTH


def test_cli_dev_hash_honors_clang_ref_env_override() -> None:
    pinned = _run_dotfiles_setup("dev-hash")
    overridden = _run_dotfiles_setup("dev-hash", env_override="0" * 40)
    assert pinned != overridden


def test_cli_empty_clang_ref_env_is_treated_as_unset() -> None:
    # An empty string must mean "use the pin" — the workflow only exports
    # CLANG_P2996_REF on a non-empty input, but defense-in-depth here keeps
    # the canonical build byte-identical even if an empty value leaks in.
    assert _run_dotfiles_setup("p2996-hash", env_override="") == _run_dotfiles_setup(
        "p2996-hash"
    )


def test_cli_base_hash_ignores_clang_ref_env_override() -> None:
    # The base hash predates the clang compile and must be invariant under
    # a p2996 ref override (only p2996/dev tiers depend on it).
    assert _run_dotfiles_setup("base-hash", env_override="0" * 40) == (
        _run_dotfiles_setup("base-hash")
    )


# ──────────────────────────────────────────────────────────────────────
# DevHashInputs validation
# ──────────────────────────────────────────────────────────────────────


def test_dev_hash_is_stable_for_fixed_inputs() -> None:
    inputs = _stub_dev_inputs()
    assert compute_dev_hash(inputs) == compute_dev_hash(inputs)
    assert len(compute_dev_hash(inputs)) == HASH_LENGTH


def test_dev_hash_is_lowercase_hex() -> None:
    assert re.fullmatch(r"[0-9a-f]+", compute_dev_hash(_stub_dev_inputs()))


def test_dev_hash_changes_when_base_hash_changes() -> None:
    base = _stub_dev_inputs()
    bumped = _stub_dev_inputs(base_hash="ffffffffffffffff")
    assert compute_dev_hash(base) != compute_dev_hash(bumped)


def test_dev_hash_changes_when_p2996_hash_changes() -> None:
    base = _stub_dev_inputs()
    bumped = _stub_dev_inputs(p2996_hash="ffffffffffffffff")
    assert compute_dev_hash(base) != compute_dev_hash(bumped)


def test_dev_hash_changes_when_dockerfile_digest_changes() -> None:
    base = _stub_dev_inputs()
    bumped = _stub_dev_inputs(dockerfile_digest="f" * 64)
    assert compute_dev_hash(base) != compute_dev_hash(bumped)


def test_dev_hash_changes_when_dev_target_digest_changes() -> None:
    base = _stub_dev_inputs()
    bumped = _stub_dev_inputs(dev_target_digest="f" * 64)
    assert compute_dev_hash(base) != compute_dev_hash(bumped)


def test_dev_hash_changes_when_runtime_config_digest_changes() -> None:
    base = _stub_dev_inputs()
    bumped = _stub_dev_inputs(runtime_config_digest="f" * 64)
    assert compute_dev_hash(base) != compute_dev_hash(bumped)


def test_dev_hash_changes_when_runtime_lock_digest_changes() -> None:
    base = _stub_dev_inputs()
    bumped = _stub_dev_inputs(runtime_lock_digest="f" * 64)
    assert compute_dev_hash(base) != compute_dev_hash(bumped)


def test_dev_hash_changes_when_platform_changes() -> None:
    base = _stub_dev_inputs()
    bumped = _stub_dev_inputs(platform="linux/arm64")
    assert compute_dev_hash(base) != compute_dev_hash(bumped)


def test_dev_inputs_reject_short_base_hash() -> None:
    with pytest.raises(ValueError, match="base_hash"):
        _stub_dev_inputs(base_hash="abc")


def test_dev_inputs_reject_uppercase_p2996_hash() -> None:
    with pytest.raises(ValueError, match="p2996_hash"):
        _stub_dev_inputs(p2996_hash="ABCDEF0123456789")


def test_dev_inputs_reject_short_dockerfile_digest() -> None:
    with pytest.raises(ValueError, match="dockerfile_digest"):
        _stub_dev_inputs(dockerfile_digest="abc")


def test_dev_inputs_reject_empty_platform() -> None:
    with pytest.raises(ValueError, match="platform"):
        _stub_dev_inputs(platform="")


def test_dev_hash_kind_namespacing_differs_from_base_and_p2996() -> None:
    # Even with colliding digest material, the kind= prefix keeps the
    # three tiers in separate namespaces so a value can't be reused.
    shared = "a" * 16
    base = compute_base_hash(
        BaseHashInputs(
            base_image="x",
            platform="x",
            base_section_digest="a" * 64,
            mise_lock_digest="a" * 64,
            mise_system_config_digest="a" * 64,
            shared_config_digest="a" * 64,
            hk_config_digest="a" * 64,
        )
    )
    dev = compute_dev_hash(_stub_dev_inputs())
    assert base != dev
    assert shared != dev


# ──────────────────────────────────────────────────────────────────────
# Bake target extraction
# ──────────────────────────────────────────────────────────────────────


def test_extract_bake_target_block_handles_nested_braces() -> None:
    bake = (
        'target "dev" {\n'
        "  args = {\n"
        '    USER = "x"\n'
        "  }\n"
        "}\n"
        'target "other" { target = "x" }\n'
    )
    block = _extract_bake_target_block(bake, "dev")
    assert block.startswith('target "dev"')
    assert block.endswith("}")
    assert "USER" in block
    # Must NOT bleed into the sibling target.
    assert "other" not in block


def test_extract_bake_target_block_missing_raises() -> None:
    with pytest.raises(ValueError, match="not found"):
        _extract_bake_target_block('target "dev" { }', "missing")


def test_extract_bake_target_block_unbalanced_raises() -> None:
    with pytest.raises(ValueError, match="unbalanced"):
        _extract_bake_target_block('target "dev" {\n  args = {\n', "dev")


# ──────────────────────────────────────────────────────────────────────
# Repo-level dev hash (gather + compute roundtrips)
# ──────────────────────────────────────────────────────────────────────


def test_gather_and_compute_repo_dev_hash_roundtrip(tmp_path: Path) -> None:
    _seed_repo(tmp_path)
    inputs = gather_dev_inputs(tmp_path, base_hash="0" * 16, p2996_hash="1" * 16)
    assert inputs.platform == "linux/amd64/v2"
    digest_a = compute_repo_dev_hash(tmp_path)
    digest_b = compute_repo_dev_hash(tmp_path)
    assert digest_a == digest_b
    assert len(digest_a) == HASH_LENGTH


def test_repo_dev_hash_changes_when_final_stage_modified(tmp_path: Path) -> None:
    # A final-stage edit (OUTSIDE the base/p2996 sentinels) leaves base
    # and p2996 hashes untouched but MUST bust dev-hash — this is the
    # whole-Dockerfile coverage that prevents skipping smoke on a
    # changed image.
    _seed_repo(tmp_path)
    base_before = compute_repo_base_hash(tmp_path)
    p2996_before = compute_repo_p2996_hash(tmp_path)
    dev_before = compute_repo_dev_hash(tmp_path)
    dockerfile = tmp_path / ".devcontainer" / "Dockerfile"
    dockerfile.write_text(
        dockerfile.read_text().replace("RUN echo final-stage", "RUN echo changed")
    )
    assert compute_repo_base_hash(tmp_path) == base_before
    assert compute_repo_p2996_hash(tmp_path) == p2996_before
    assert compute_repo_dev_hash(tmp_path) != dev_before


def test_repo_dev_hash_changes_when_dev_target_modified(tmp_path: Path) -> None:
    _seed_repo(tmp_path)
    before = compute_repo_dev_hash(tmp_path)
    bake = tmp_path / "docker-bake.hcl"
    bake.write_text(
        bake.read_text().replace(
            'DEVCONTAINER_USERNAME = "devcontainer"',
            'DEVCONTAINER_USERNAME = "ray"',
        )
    )
    assert compute_repo_dev_hash(tmp_path) != before


def test_repo_dev_hash_changes_when_base_section_modified(tmp_path: Path) -> None:
    # Base-section edit bumps base-hash → p2996-hash → dev-hash (chain).
    _seed_repo(tmp_path)
    before = compute_repo_dev_hash(tmp_path)
    dockerfile = tmp_path / ".devcontainer" / "Dockerfile"
    dockerfile.write_text(
        dockerfile.read_text().replace("RUN apt-get update", "RUN apt-get install foo")
    )
    assert compute_repo_dev_hash(tmp_path) != before


def test_cli_base_and_p2996_hashes_are_distinct() -> None:
    base = _run_dotfiles_setup("base-hash")
    p2996 = _run_dotfiles_setup("p2996-hash")
    assert base != p2996
