# Copyright (c) 2026 Raymond Manaloto
"""Generate the `codex-astra-*` lanes from the authored `codex-sol-*` lanes.

The two model lanes differ in exactly one thing — which model `codex exec` is
pinned to — while sharing ~270 lines of evidence discipline, hard limits and
return format per role. Authoring both would mean maintaining that body twice,
and the drift would be SILENT: nothing fails when only one twin is updated.

So `codex-sol-<role>` is the source of truth and `codex-astra-<role>` is its
mirror, exactly as `.claude/skills` is to `.agents/skills`
(``skills_mirror.py``). ``--check`` is the read-only gate; the bare form writes.

⚠️ The substitution is deliberately narrow — the lane name and the model string,
nothing else. A wider rewrite would let the mirror diverge in meaning from the
source it claims to mirror, which is the failure this module exists to prevent.
"""

from __future__ import annotations

import logging
import re
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from pathlib import Path

logger = logging.getLogger(__name__)

SOL_PREFIX = "codex-sol-"
ASTRA_PREFIX = "codex-astra-"

SOL_MODEL = "gpt-5.6-sol"
ASTRA_MODEL = "gpt-6-astra"

CLAUDE_AGENT_DIR = ".claude/agents"
CODEX_AGENT_DIR = ".codex/agents"

#: Stamped into every generated file so a hand edit is obviously in the wrong
#: place. The `--check` arm re-renders and compares, so an edit here loses.
GENERATED_NOTICE = (
    "GENERATED by `mise run codex-lane-mirror` from the codex-sol-* lane of the "
    "same role. Do NOT edit: `-- --check` re-renders and fails on any drift. "
    "Change the sol lane instead."
)


def roles(root: Path) -> list[str]:
    """Every role with an authored sol lane, by its `.md` wrapper."""
    directory = root / CLAUDE_AGENT_DIR
    if not directory.is_dir():
        return []
    return sorted(
        p.name[len(SOL_PREFIX) : -len(".md")]
        for p in directory.iterdir()
        if p.is_file() and p.name.startswith(SOL_PREFIX) and p.name.endswith(".md")
    )


def render_md(source_text: str) -> str:
    """The astra `.md` for a sol `.md`: rename, re-model, stamp as generated."""
    text = source_text.replace(SOL_PREFIX, ASTRA_PREFIX).replace(SOL_MODEL, ASTRA_MODEL)
    # The notice cannot precede the frontmatter — a `.md` agent must open with
    # `---` at byte 0 — so it goes immediately after the closing fence.
    match = re.match(r"\A---\n.*?\n---\n", text, re.DOTALL)
    if match is None:
        return text
    end = match.end()
    return f"{text[:end]}\n<!-- {GENERATED_NOTICE} -->\n{text[end:]}"


def render_toml(source_text: str) -> str:
    """The astra `.toml` for a sol `.toml`: same substitution, TOML comment."""
    text = source_text.replace(SOL_PREFIX, ASTRA_PREFIX).replace(SOL_MODEL, ASTRA_MODEL)
    return f"# {GENERATED_NOTICE}\n{text}"


def mirror_paths(root: Path) -> list[tuple[Path, Path, str]]:
    """`(source, target, kind)` for every file the mirror owns."""
    pairs: list[tuple[Path, Path, str]] = []
    for role in roles(root):
        pairs.append(
            (
                root / CLAUDE_AGENT_DIR / f"{SOL_PREFIX}{role}.md",
                root / CLAUDE_AGENT_DIR / f"{ASTRA_PREFIX}{role}.md",
                "md",
            )
        )
        pairs.append(
            (
                root / CODEX_AGENT_DIR / f"{SOL_PREFIX}{role}.toml",
                root / CODEX_AGENT_DIR / f"{ASTRA_PREFIX}{role}.toml",
                "toml",
            )
        )
    return pairs


def _rendered(source: Path, kind: str) -> str:
    text = source.read_text(encoding="utf-8")
    return render_md(text) if kind == "md" else render_toml(text)


def find_drift(root: Path) -> list[str]:
    """Every generated file that is missing or no longer matches its source."""
    findings: list[str] = []
    for source, target, kind in mirror_paths(root):
        if not source.is_file():
            findings.append(f"{source.relative_to(root)}: sol source missing")
            continue
        expected = _rendered(source, kind)
        rel = target.relative_to(root)
        if not target.is_file():
            findings.append(f"{rel}: missing — run `mise run codex-lane-mirror`")
        elif target.read_text(encoding="utf-8") != expected:
            findings.append(f"{rel}: drifted from {source.relative_to(root)}")
    # A stale astra lane whose sol source was deleted must fail too, or the map
    # rots silently after a role is retired.
    expected_targets = {target for _, target, _ in mirror_paths(root)}
    for directory, suffix in (
        (root / CLAUDE_AGENT_DIR, ".md"),
        (root / CODEX_AGENT_DIR, ".toml"),
    ):
        if not directory.is_dir():
            continue
        for path in sorted(directory.iterdir()):
            if not path.is_file() or not path.name.startswith(ASTRA_PREFIX):
                continue
            if path.name.endswith(suffix) and path not in expected_targets:
                findings.append(
                    f"{path.relative_to(root)}: no codex-sol-* source — stale"
                )
    return findings


def write_mirror(root: Path) -> list[str]:
    """Write every generated file; return the ones that changed."""
    written: list[str] = []
    for source, target, kind in mirror_paths(root):
        if not source.is_file():
            continue
        expected = _rendered(source, kind)
        if target.is_file() and target.read_text(encoding="utf-8") == expected:
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(expected, encoding="utf-8")
        written.append(str(target.relative_to(root)))
    return written


def codex_lane_mirror_main(repo_root: Path, *, check: bool = False) -> int:
    """`--check` gates; the bare form writes. Exit 1 only on drift under check."""
    if check:
        findings = find_drift(repo_root)
        if findings:
            for finding in findings:
                logger.error("codex-lane-mirror DRIFT: %s", finding)
            return 1
        count = len(mirror_paths(repo_root))
        logger.info(
            "codex-lane-mirror OK: %d generated file(s) match their sol source",
            count,
        )
        return 0
    written = write_mirror(repo_root)
    if written:
        for path in written:
            logger.info("codex-lane-mirror WROTE: %s", path)
    else:
        logger.info("codex-lane-mirror OK: the astra lanes already match")
    return 0
