# Copyright (c) 2026 Raymond Manaloto
"""Codex configuration schema management.

Generates and validates the codex app-server JSON schema against the installed
codex version. Schema is generated from the exact installed version to ensure
all settings and environment variables are searchable locally.
"""

from __future__ import annotations

import json
import pathlib
import shutil
import subprocess
import tempfile
from typing import TYPE_CHECKING, Any, Final

if TYPE_CHECKING:
    from pathlib import Path


VERSION_STAMP_FILENAME: Final = "codex_app_server_protocol.version"


def get_installed_codex_version() -> str:
    """Get the installed codex CLI version."""
    result = subprocess.run(
        ["mise", "exec", "--", "codex", "--version"],
        capture_output=True,
        text=True,
        check=True,
    )
    # Output format: "codex-cli 0.154.0"
    return result.stdout.strip().split()[-1]


def schema_path(repo_root: Path) -> Path:
    """Return the path to the generated codex app-server schema bundle."""
    return repo_root / "schemas" / "codex_app_server_protocol.schemas.json"


def stamp_path(repo_root: Path) -> Path:
    """Return the sidecar recording which codex version emitted the schema."""
    return repo_root / "schemas" / VERSION_STAMP_FILENAME


def read_stamp(repo_root: Path) -> str | None:
    """Read the generated schema's codex version sidecar, if present."""
    try:
        version = stamp_path(repo_root).read_text(encoding="utf-8").strip()
    except FileNotFoundError:
        return None
    return version or None


def validate_schema_exists(repo_root: Path) -> bool:
    """Check if the codex schema has been generated."""
    return schema_path(repo_root).exists()


def load_schema(repo_root: Path) -> dict[str, Any] | None:
    """Load the generated codex app-server schema."""
    path = schema_path(repo_root)
    if not path.exists():
        return None
    with path.open() as f:
        return json.load(f)


def check_schema_currency(repo_root: Path, current_version: str) -> tuple[bool, str]:
    """Check if the generated schema matches the installed codex version.

    Args:
        repo_root: Root of the dotfiles repository
        current_version: Current installed codex version (e.g., "0.154.0")

    Returns:
        (is_current, message): is_current is True if schema is current,
        message explains the status
    """
    schema: object | None = None
    generated_version: str | None = None
    failure: str | None = None
    try:
        schema = load_schema(repo_root)
    except json.JSONDecodeError as exc:
        failure = f"Schema at {schema_path(repo_root)} is invalid JSON: {exc}"
    except OSError as exc:
        failure = f"Schema at {schema_path(repo_root)} cannot be read: {exc}"

    if failure is None and not schema:
        failure = (
            f"Schema not found at {schema_path(repo_root)}. "
            "Run 'mise run codex-schema-generate' to create it."
        )
    elif failure is None and not isinstance(schema, dict):
        failure = "Schema is not valid JSON"

    if failure is None:
        try:
            generated_version = read_stamp(repo_root)
        except OSError as exc:
            failure = f"Version stamp at {stamp_path(repo_root)} cannot be read: {exc}"

    if failure is None and generated_version is None:
        failure = (
            f"Version stamp not found at {stamp_path(repo_root)}. "
            "Run 'mise run codex-schema-generate' to regenerate the schema."
        )
    elif failure is None and generated_version != current_version:
        failure = (
            f"Schema was generated by codex {generated_version}, but codex "
            f"{current_version} is installed. Run 'mise run codex-schema-generate'."
        )

    if failure is not None:
        return (False, failure)

    msg = (
        f"Schema matches installed codex {current_version}. "
        "Regenerate with 'mise run codex-schema-generate' after a codex upgrade."
    )
    return (True, msg)


#: The three keys a custom agent file MUST define, per codex's own schema table.
#: They are agent-file-only: `config.toml` declares `developer_instructions` but
#: NOT `name` or `description`, and it sets `additionalProperties: false` — so an
#: agent file pointed at the raw config schema is rejected for two of its three
#: required keys. Measured 2026-09-14: all six specialists went INVALID that way.
AGENT_ONLY_KEYS: Final = ("name", "description")


def config_schema_path(repo_root: Path) -> Path:
    """The vendored codex `config.toml` JSON schema."""
    return repo_root / "schemas" / "codex-config.json"


def agent_schema_path(repo_root: Path) -> Path:
    """The DERIVED schema that validates a `.codex/agents/*.toml` file."""
    return repo_root / "schemas" / "codex-agent.json"


def derive_agent_schema(config_schema: dict[str, Any]) -> dict[str, Any]:
    """Build the agent-file schema from codex's `config.toml` schema.

    An agent file accepts every `config.toml` key PLUS `name` and
    `description`, and requires those two plus `developer_instructions`.

    `additionalProperties` stays False deliberately: that is what makes a typo'd
    or wrong-typed key an ERROR rather than silent. Codex itself drops an invalid
    agent file with no message, no warning and no exit code, so this schema is
    the only thing standing between a malformed file and an agent that simply
    does not exist.
    """
    return {
        "$schema": config_schema.get(
            "$schema", "http://json-schema.org/draft-07/schema#"
        ),
        "title": "Codex custom agent file (.codex/agents/*.toml)",
        "description": (
            "DERIVED from schemas/codex-config.json. Regenerate with "
            "`mise run codex-schema-generate`; never hand-edit."
        ),
        "type": "object",
        "additionalProperties": False,
        "required": ["name", "description", "developer_instructions"],
        "properties": {
            "name": {
                "type": "string",
                "description": (
                    "Agent name codex uses when spawning. This is the identity; "
                    "the filename is convention only."
                ),
            },
            "description": {
                "type": "string",
                "description": (
                    "When codex should use this agent. THIS IS THE ROUTING "
                    "SIGNAL — overlapping descriptions send work to the wrong agent."
                ),
            },
            **config_schema.get("properties", {}),
        },
        "definitions": config_schema.get("definitions", {}),
    }


def generate_schema(repo_root: Path, output_dir: Path | None = None) -> bool:
    """Generate the codex app-server JSON schema for the installed version.

    Args:
        repo_root: Root of the dotfiles repository
        output_dir: Directory to write schemas (default: schemas/)

    Returns:
        True if generation succeeded, False otherwise
    """
    if output_dir is None:
        output_dir = repo_root / "schemas"

    output_dir.mkdir(parents=True, exist_ok=True)

    # Generate into a TEMPORARY directory and keep only the bundles.
    #
    # `generate-json-schema --out <dir>` writes the whole app-server protocol
    # surface: measured 2026-09-14, 305 files including a per-message schema for
    # every request, response and notification, plus `v1/` and `v2/` subtrees.
    # `schemas/` is a curated vendoring directory that held four files, and
    # `_schema_path()` reads exactly ONE of the generated artifacts — the bundle,
    # which already contains every per-message definition. Committing the other
    # 303 would add a megabyte of redundancy to a reviewed directory.
    staging = tempfile.mkdtemp(prefix="codex-schema-")
    try:
        result = subprocess.run(
            [
                "mise",
                "exec",
                "--",
                "codex",
                "app-server",
                "generate-json-schema",
                "--out",
                staging,
            ],
            capture_output=True,
            text=True,
            check=False,
        )
        if result.returncode != 0:
            return False

        # Keep ONLY the bundles. `schema_path()` reads the first of these; the
        # v2 sibling is kept because the two describe different protocol
        # versions and a reader may need either. Everything else the generator
        # emitted is per-message duplication already inside the bundle.
        kept = 0
        for name in (
            "codex_app_server_protocol.schemas.json",
            "codex_app_server_protocol.v2.schemas.json",
        ):
            src = pathlib.Path(staging) / name
            if src.is_file():
                shutil.copy2(src, output_dir / name)
                kept += 1

        if kept == 0:
            return False

        config_schema = json.loads(
            config_schema_path(repo_root).read_text(encoding="utf-8")
        )
        if not isinstance(config_schema, dict):
            return False
        derived_schema = derive_agent_schema(config_schema)
        (output_dir / agent_schema_path(repo_root).name).write_text(
            json.dumps(derived_schema, indent=2) + "\n",
            encoding="utf-8",
        )
        (output_dir / VERSION_STAMP_FILENAME).write_text(
            f"{get_installed_codex_version()}\n",
            encoding="utf-8",
        )
    except OSError, json.JSONDecodeError, subprocess.SubprocessError:
        return False
    else:
        return True
    finally:
        shutil.rmtree(staging, ignore_errors=True)
