# Copyright (c) 2026 Raymond Manaloto
"""Build-time gates for Claude Code function-hook modules (#1026).

Function-hook runtime failures are silent and fail open, so the repository
checks the two classes the harness can establish before loading a plugin:
Claude Code validates the module's syntax and event names, while TypeScript
checks handler return shapes against declarations generated by `/plugin-types`.
The explicit typed-register assertion is the bridge between them; without it,
TypeScript accepts an ``any``-typed module and the second gate proves nothing.
"""

from __future__ import annotations

import json
import os
import re
import subprocess
import sys
import tempfile
import tomllib
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    from collections.abc import Mapping, Sequence

FIXTURE_ROOT = "tests/fixtures/fnhook"

_TYPE_FILENAMES = ("claude-code.d.ts", "claude-code-mcp.d.ts")

# The mise tool names whose pins back the two gate binaries. `mise exec -- <bin>`
# is NOT enough: with no tool named it resolves the bare SHIM, and mise then has
# no version to map it to. Measured on a GitHub runner 2026-09-12 — both tools
# installed fine and the gate still died on
# `mise ERROR No version is set for shim: claude`. It passed locally because a
# shim resolves on this Mac, so the host is not a control arm for CI.
#
# The version is READ FROM `mise.toml` rather than written here, so a pin bump
# cannot leave the invocation naming a stale version.
# This module lives at python/src/dotfiles_setup/, so the repo root is three
# parents up. The tool spec always comes from the REPO's mise.toml, never from
# whatever cwd a gate happens to run in — `_generate_types` runs in a temp dir.
_REPO_ROOT = Path(__file__).resolve().parents[3]

CLAUDE_TOOL = "npm:@anthropic-ai/claude-code"
TSC_TOOL = "npm:typescript"


def tool_spec(repo_root: Path, tool: str) -> str:
    """`<tool>@<version>` using the pin in `mise.toml`, so the two cannot drift."""
    config = tomllib.loads((repo_root / "mise.toml").read_text(encoding="utf-8"))
    tools = config.get("tools", {})
    version = tools.get(tool)
    if not isinstance(version, str):
        message = (
            f"{tool} is not pinned as an exact version in mise.toml — the gate "
            f"cannot name a tool it has no pin for (found {version!r})"
        )
        raise TypeError(message)
    return f"{tool}@{version}"


_FUNCTION_HOOKS_FLAG = "CLAUDE_CODE_ENABLE_FUNCTION_HOOKS"
_COMMAND_TIMEOUT_SECONDS = 120.0
_TYPED_REGISTER_RE = re.compile(
    r"\bexport\s+const\s+register\s*:\s*Register\b",
)
_ENVIRONMENT_INTERFACE_NAMES = (
    b"BuiltinToolInputs",
    b"BuiltinToolResults",
)
_NORMALIZED_INTERFACE_BODY = (
    b"    // Built-in tool inventory varies by generating session.\n"
)


@dataclass(frozen=True)
class GateResult:
    """One gate invocation's observable result."""

    rc: int
    stdout: str = ""
    stderr: str = ""

    @property
    def ok(self) -> bool:
        """Whether the gate passed."""
        return self.rc == 0


class Runner(Protocol):
    """Injected subprocess boundary used by unit tests and production."""

    def __call__(
        self,
        command: list[str],
        *,
        cwd: Path,
        env: Mapping[str, str] | None = None,
        input_text: str | None = None,
    ) -> GateResult:
        """Run ``command`` and return its captured streams."""
        ...


def default_runner(
    command: list[str],
    *,
    cwd: Path,
    env: Mapping[str, str] | None = None,
    input_text: str | None = None,
) -> GateResult:
    """Run one bounded command; missing binaries and timeouts fail loudly."""
    child_env = os.environ.copy()
    if env is not None:
        child_env.update(env)
    try:
        completed = subprocess.run(
            command,
            cwd=cwd,
            env=child_env,
            input=input_text,
            capture_output=True,
            text=True,
            check=False,
            timeout=_COMMAND_TIMEOUT_SECONDS,
        )
    except subprocess.TimeoutExpired:
        return GateResult(rc=124, stderr="command timed out")
    except OSError as exc:
        return GateResult(rc=127, stderr=str(exc))
    return GateResult(
        rc=completed.returncode,
        stdout=completed.stdout,
        stderr=completed.stderr,
    )


def discover_plugin_dirs(
    repo_root: Path,
    *,
    include_fixtures: bool = False,
) -> list[Path]:
    """Return dirs containing both required Claude Code plugin manifests.

    The set is derived from the tree. Only :data:`FIXTURE_ROOT` is excluded
    from the production gate; a plugin elsewhere under ``tests/`` still counts.
    """
    fixture_root = (repo_root / FIXTURE_ROOT).resolve()
    discovered: list[Path] = []
    for plugin_manifest in repo_root.rglob(".claude-plugin/plugin.json"):
        plugin_dir = plugin_manifest.parent.parent
        if not (plugin_dir / "hooks" / "hooks.json").is_file():
            continue
        if not include_fixtures and plugin_dir.resolve().is_relative_to(fixture_root):
            continue
        discovered.append(plugin_dir)
    return sorted(discovered)


def validate_plugin(
    plugin_dir: Path,
    *,
    runner: Runner = default_runner,
) -> GateResult:
    """Run Claude Code's strict static validator for one complete plugin."""
    return runner(
        [
            "mise",
            "exec",
            tool_spec(_REPO_ROOT, CLAUDE_TOOL),
            "--",
            "claude",
            "plugin",
            "validate",
            "--strict",
            str(plugin_dir),
        ],
        cwd=Path.cwd(),
    )


def _module_paths(dirs: Sequence[Path]) -> list[Path]:
    """Resolve every function-hook module declared by ``dirs``."""
    modules: set[Path] = set()
    for plugin_dir in dirs:
        hooks_manifest = plugin_dir / "hooks" / "hooks.json"
        try:
            payload = json.loads(hooks_manifest.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            msg = f"{hooks_manifest}: cannot read hooks manifest: {exc}"
            raise ValueError(msg) from exc
        declared = payload.get("modules") if isinstance(payload, dict) else None
        if not isinstance(declared, list) or not all(
            isinstance(item, str) and item for item in declared
        ):
            msg = f"{hooks_manifest}: modules must be a non-empty string list"
            raise ValueError(msg)
        for relative_path in declared:
            module = (hooks_manifest.parent / relative_path).resolve()
            if not module.is_file():
                msg = (
                    f"{hooks_manifest}: declared module does not exist: {relative_path}"
                )
                raise ValueError(msg)
            modules.add(module)
    return sorted(modules)


def assert_modules_are_typed(dirs: list[Path]) -> GateResult:
    """Require every declared module to export ``register: Register``."""
    try:
        modules = _module_paths(dirs)
    except ValueError as exc:
        return GateResult(rc=1, stdout=f"{exc}\n")

    untyped = [
        module
        for module in modules
        if _TYPED_REGISTER_RE.search(module.read_text(encoding="utf-8")) is None
    ]
    if not untyped:
        return GateResult(rc=0)
    rendered = "\n".join(f"untyped function-hook module: {path}" for path in untyped)
    return GateResult(rc=1, stdout=f"{rendered}\n")


def typecheck_modules(
    dirs: list[Path],
    *,
    runner: Runner = default_runner,
) -> GateResult:
    """Type-check exactly the discovered modules against generated declarations."""
    repo_root = Path.cwd().resolve()
    try:
        modules = _module_paths(dirs)
    except ValueError as exc:
        return GateResult(rc=1, stdout=f"{exc}\n")

    files = [repo_root / ".claude" / "types" / name for name in _TYPE_FILENAMES]
    missing = [path for path in files if not path.is_file()]
    if missing:
        rendered = ", ".join(str(path) for path in missing)
        return GateResult(
            rc=1,
            stdout=f"missing function-hook declarations: {rendered}\n",
        )

    with tempfile.TemporaryDirectory(prefix="fnhook-tsc-") as temp_dir:
        project = Path(temp_dir) / "tsconfig.json"
        project.write_text(
            json.dumps(
                {
                    "extends": str(repo_root / "tsconfig.json"),
                    "files": [str(path.resolve()) for path in [*files, *modules]],
                },
                indent=2,
            )
            + "\n",
            encoding="utf-8",
        )
        return runner(
            [
                "mise",
                "exec",
                tool_spec(_REPO_ROOT, TSC_TOOL),
                "--",
                "tsc",
                "--noEmit",
                "--project",
                str(project),
            ],
            cwd=repo_root,
        )


def _generate_types(work_root: Path, *, runner: Runner) -> GateResult:
    """Invoke `/plugin-types`; its rc is intentionally not interpreted.

    `work_root` is a temp dir, so the tool spec is read from the REPO's
    `mise.toml`, not from the cwd the command runs in.
    """
    return runner(
        [
            "mise",
            "exec",
            tool_spec(_REPO_ROOT, CLAUDE_TOOL),
            "--",
            "claude",
            "-p",
            "/plugin-types",
            "--permission-mode",
            "bypassPermissions",
        ],
        cwd=work_root,
        env={_FUNCTION_HOOKS_FLAG: "1"},
        input_text="",
    )


def _generated_files(work_root: Path) -> list[Path]:
    """The two files one successful `/plugin-types` invocation must write."""
    return [work_root / ".claude" / "types" / name for name in _TYPE_FILENAMES]


def _missing_or_empty(paths: Sequence[Path]) -> list[Path]:
    """Return generated outputs that cannot be used as declarations."""
    return [path for path in paths if not path.is_file() or path.stat().st_size == 0]


def normalize_claude_code_declarations(source: bytes) -> bytes:
    """Replace only the two environment-dependent built-in-tool bodies.

    ``/plugin-types`` writes the generating session's available tools into two
    declaration-merging interfaces. The plugin API before and after them is
    stable and remains byte-sensitive. Requiring exactly one generated form of
    each interface makes a generator-format change fail closed.
    """
    normalized = source
    for name in _ENVIRONMENT_INTERFACE_NAMES:
        opening = b"  interface " + name + b" {\n"
        if normalized.count(opening) != 1:
            msg = f"expected exactly one generated {name.decode()} interface"
            raise ValueError(msg)
        body_start = normalized.index(opening) + len(opening)
        closing = b"\n  }\n}"
        body_end = normalized.find(closing, body_start)
        if body_end < 0:
            msg = f"generated {name.decode()} interface has no closing boundary"
            raise ValueError(msg)
        normalized = (
            normalized[:body_start]
            + _NORMALIZED_INTERFACE_BODY
            + normalized[body_end + 1 :]
        )
    return normalized


def drift_comparable_files(repo_root: Path) -> tuple[Path, ...]:
    """The declarations whose drift is meaningful to compare.

    `claude-code-mcp.d.ts` is EXCLUDED. It is not merely session-flavoured
    like the builtin-tool interfaces — it is per-session in its entirety, and
    its own header says so: with nothing connected it reports "no MCP tools
    are connected, so it is empty (every mcp__* tool stays loosely typed)",
    while a session with servers attached reports "170 MCP tools from 12
    servers" (both measured 2026-09-12, same machine, minutes apart). There is
    no stable subset to normalize down to, and nothing the type gate binds
    lives in it, so comparing it can only produce false drift.

    `claude-code.d.ts` IS compared, after normalization — that file carries the
    plugin API the gate actually consumes, and its normalizer has a control arm
    asserting an API-surface mutation is still detected.
    """
    return tuple(
        path for path in _generated_files(repo_root) if path.name != _TYPE_FILENAMES[1]
    )


def _comparable_declaration_bytes(path: Path) -> bytes:
    """Read one declaration, normalizing the session-dependent regions away."""
    source = path.read_bytes()
    if path.name == _TYPE_FILENAMES[0]:
        return normalize_claude_code_declarations(source)
    return source


def _check_types_current(repo_root: Path, *, runner: Runner) -> GateResult:
    """Compare stable declaration bytes with a normalized fresh generation."""
    committed = _generated_files(repo_root)
    missing = _missing_or_empty(committed)
    if missing:
        rendered = ", ".join(str(path) for path in missing)
        return GateResult(rc=1, stdout=f"missing committed declarations: {rendered}\n")

    with tempfile.TemporaryDirectory(prefix="fnhook-types-") as temp_dir:
        generated_root = Path(temp_dir)
        invocation = _generate_types(generated_root, runner=runner)
        generated = _generated_files(generated_root)
        missing = _missing_or_empty(generated)
        if missing:
            rendered = ", ".join(str(path) for path in missing)
            return GateResult(
                rc=1,
                stdout=invocation.stdout
                + f"/plugin-types did not write non-empty outputs: {rendered}\n",
                stderr=invocation.stderr,
            )
        try:
            drifted = [
                expected
                for expected, actual in zip(
                    drift_comparable_files(repo_root),
                    drift_comparable_files(generated_root),
                    strict=True,
                )
                if _comparable_declaration_bytes(expected)
                != _comparable_declaration_bytes(actual)
            ]
        except ValueError as exc:
            return GateResult(
                rc=1,
                stdout=invocation.stdout
                + f"cannot normalize function-hook declarations: {exc}\n",
                stderr=invocation.stderr,
            )
        if drifted:
            rendered = ", ".join(str(path) for path in drifted)
            return GateResult(
                rc=1,
                stdout=invocation.stdout
                + f"function-hook declarations drifted: {rendered}; "
                "run `mise run fnhook-types-refresh`\n",
                stderr=invocation.stderr,
            )
        return GateResult(
            rc=0,
            stdout=invocation.stdout,
            stderr=invocation.stderr,
        )


def _emit(result: GateResult) -> None:
    """Preserve the external tools' measured stdout/stderr split."""
    sys.stdout.write(result.stdout)
    sys.stderr.write(result.stderr)


def fnhook_gates_main(
    argv: Sequence[str] | None = None,
    *,
    runner: Runner = default_runner,
) -> int:
    """Run all function-hook build gates for the current repository."""
    if argv:
        sys.stderr.write("fnhook-gates takes no arguments\n")
        return 2
    repo_root = Path.cwd().resolve()
    plugin_dirs = discover_plugin_dirs(repo_root)
    results = [validate_plugin(path, runner=runner) for path in plugin_dirs]
    results.extend(
        (
            assert_modules_are_typed(plugin_dirs),
            typecheck_modules(plugin_dirs, runner=runner),
            _check_types_current(repo_root, runner=runner),
        )
    )
    rc = 0
    for result in results:
        _emit(result)
        if not result.ok:
            rc = 1
    return rc


def _restore_generated_files(
    paths: Sequence[Path],
    previous: Mapping[Path, bytes | None],
) -> None:
    """Restore declaration bytes when regeneration writes an incomplete pair."""
    for path in paths:
        old_bytes = previous[path]
        if old_bytes is None:
            path.unlink(missing_ok=True)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(old_bytes)


def fnhook_types_refresh_main(
    argv: Sequence[str] | None = None,
    *,
    runner: Runner = default_runner,
) -> int:
    """Regenerate both function-hook declaration files from pinned Claude Code."""
    if argv:
        sys.stderr.write("fnhook-types-refresh takes no arguments\n")
        return 2
    repo_root = Path.cwd().resolve()
    generated = _generated_files(repo_root)
    previous = {
        path: path.read_bytes() if path.is_file() else None for path in generated
    }
    for path in generated:
        path.unlink(missing_ok=True)

    invocation = _generate_types(repo_root, runner=runner)
    _emit(invocation)
    missing = _missing_or_empty(generated)
    if not missing:
        return 0

    _restore_generated_files(generated, previous)
    rendered = ", ".join(str(path) for path in missing)
    sys.stdout.write(f"/plugin-types did not write non-empty outputs: {rendered}\n")
    return 1
