# Copyright (c) 2026 Raymond Manaloto
"""Record executed GitHub searches, rerun with controls, and report drift."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import secrets
import subprocess
import sys
import tempfile
import tomllib
from collections import Counter
from dataclasses import dataclass, replace
from datetime import UTC, date, datetime
from pathlib import Path
from typing import TYPE_CHECKING, cast
from urllib.parse import quote_plus

import tomli_w

from dotfiles_setup import codec
from dotfiles_setup.generated.saved_search_file import (
    UNSET,
    Cadence,
    CodeRole,
    Collect,
    Result,
    SavedSearchFile,
    UnsetType,
    Watch,
    WatchKind,
)
from dotfiles_setup.generated.saved_search_snapshot import (
    Kind,
    RerunStatus,
    SavedSearchSnapshot,
    SearchControl,
    WatchRun,
)
from dotfiles_setup.research_fanout import (
    _GITHUB_QUERY,
    _REAL_TIMING,
    FanoutRequest,
    ProbeTiming,
    Status,
    _gh_env,
    _gh_include,
    _ProbeBoundaries,
    _repo_ok,
    _repo_root,
    default_runner,
    fan_out,
)

if TYPE_CHECKING:
    from dotfiles_setup.research_fanout import Runner

GENERATED_HEADER = (
    "# generated by research-saved-search record — edits are overwritten on the "
    "next record; copy to a new file to curate"
)
_SNAPSHOT_DIR = ".agent/kb/raw/saved-searches"
_HEALTH = "repo:cli/cli filename:README.md"
_CODE_PACE = 6.5
_SECONDS_PER_DAY = 86400
_MAX_ID = 80
_HTTP_ERROR = 400
_FILE_MODE = 0o644
# REST search returns at most 1000 results, at most 100 per page.
_PAGE_SIZE = 100
_RESULT_CAP = 1000
_COMPARABLE = {"ok", "empty-verified"}
_BLOB_REF = re.compile(r"^(https://github\.com/[^/]+/[^/]+/blob/)[^/]+/")
_REGEX_FIELDS = ("grep", "path_grep", "control_hit_grep", "control_hit_path_grep")
_SOURCE_KINDS = {
    "github-issues": WatchKind.issues,
    "github-discussions": WatchKind.discussions,
    "github-releases": WatchKind.releases,
}
_FANOUT_STATUS = {
    Status.OK: RerunStatus.ok,
    Status.EMPTY_VERIFIED: RerunStatus.empty_verified,
    Status.EMPTY_UNVERIFIED: RerunStatus.empty_unarmed,
    Status.ERROR: RerunStatus.error,
    Status.SKIPPED: RerunStatus.error,
}


class SavedSearchError(ValueError):
    """A load or usage error that must precede network activity."""


def _given[T](value: T | UnsetType, default: T) -> T:
    return default if isinstance(value, UnsetType) else value


def _resolve(root: Path, value: str) -> Path:
    return (root / value).resolve()


def _date(value: str) -> datetime:
    parsed = datetime.fromisoformat(value)
    return (
        parsed.replace(tzinfo=UTC) if parsed.tzinfo is None else parsed.astimezone(UTC)
    )


def _iso(value: object) -> str:
    if isinstance(value, datetime | date):
        return value.isoformat()
    message = "unsupported TOML value"
    raise TypeError(message)


def _invalid(path: Path, identifier: str, field: str) -> SavedSearchError:
    return SavedSearchError(f"{path}: id {identifier}: invalid {field}")


def collect_mode(watch: Watch) -> Collect:
    """The effective collect mode: an explicit `collect`, else the kind's default.

    A code QUERY defaults to `all` (Ray, 2026-10-03): only paging every hit lets
    a rerun find a new example ranked below a top-N window. Controls (must-hit,
    health, readme) need only a count above 0, and no other kind ranks, so they
    default to `top`. `collect = "top"` opts a query out.
    """
    if not isinstance(watch.collect, UnsetType):
        return watch.collect
    is_query = _given(watch.role, CodeRole.query) == CodeRole.query
    return Collect.all if watch.kind == WatchKind.code and is_query else Collect.top


def _validate_watch(watch: Watch, path: Path) -> None:
    repo = _given(watch.repo, "")
    if repo and not _repo_ok(repo):
        raise _invalid(path, watch.id, "repo")
    if watch.kind == WatchKind.releases and not repo:
        raise _invalid(path, watch.id, "repo (required for releases)")
    absent = _given(watch.control_absent, "")
    if not isinstance(watch.control_absent, UnsetType) and "{nonce}" not in absent:
        raise _invalid(path, watch.id, "control_absent (requires {nonce})")
    # Paging to the cap is how a code QUERY catches a new low-ranked example; a
    # control only needs a count above 0, and no other kind has the ranking problem.
    if _given(watch.collect, Collect.top) == Collect.all and (
        watch.kind != WatchKind.code
        or _given(watch.role, CodeRole.query) != CodeRole.query
    ):
        raise _invalid(path, watch.id, "collect (all is for code query watches only)")
    for field in _REGEX_FIELDS:
        pattern = _given(getattr(watch, field), "")
        try:
            re.compile(pattern)
        except re.error:
            raise _invalid(path, watch.id, field) from None


def _validate_watches(raw: dict[str, object], path: Path) -> set[str]:
    watches = raw.get("watch", [])
    if not isinstance(watches, list):
        raise _invalid(path, "<file>", "watch")
    ids: set[str] = set()
    for row in watches:
        identifier = (
            str(row.get("id", "<missing>")) if isinstance(row, dict) else "<missing>"
        )
        try:
            watch = codec.decode(json.dumps(row, default=_iso).encode(), Watch)
        except (ValueError, TypeError) as error:
            raise _invalid(path, identifier, str(error)) from None
        if watch.id in ids:
            raise _invalid(path, watch.id, "id (duplicate)")
        ids.add(watch.id)
        _validate_watch(watch, path)
    return ids


def load(path: Path) -> SavedSearchFile:
    """Load a tracked TOML file, validating all watches before any fetch."""
    try:
        raw = tomllib.loads(path.read_text(encoding="utf-8"))
    except OSError, ValueError:
        raise _invalid(path, "<file>", "TOML") from None
    ids = _validate_watches(raw, path)
    results = raw.get("result", [])
    fields = Result.__struct_fields__
    if isinstance(results, list):
        raw["result"] = [
            {key: value for key, value in row.items() if key in fields}
            if isinstance(row, dict)
            else row
            for row in results
        ]
    try:
        model = codec.decode(json.dumps(raw, default=_iso).encode(), SavedSearchFile)
        for result in _given(model.result, []):
            _date(result.date_run)
    except (ValueError, TypeError) as error:
        raise _invalid(path, "<file>", str(error)) from None
    for result in _given(model.result, []):
        if result.watch_id not in ids:
            sys.stderr.write(
                f"{path}: warning: result.watch_id {result.watch_id} names no watch\n"
            )
    return model


def search_id(kind: WatchKind, repo: str, query: str, role: str = "") -> str:
    """Give the same search the same bounded identifier on every recording."""
    slug = re.sub(r"[^a-z0-9-]+", "-", query.lower()).strip("-")[:40]
    digest = hashlib.sha256(f"{kind}|{repo}|{query}|{role}".encode()).hexdigest()[:8]
    prefix = f"{kind}-{repo.replace('/', '-') or 'any'}-{slug}"
    prefix = re.sub(r"-+", "-", re.sub(r"[^a-z0-9-]", "-", prefix.lower()))
    return f"{prefix[: _MAX_ID - len(digest) - 1].rstrip('-')}-{digest}"


def _atomic_write(path: Path, data: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(dir=path.parent, delete=False) as stream:
            temporary = Path(stream.name)
            stream.write(data)
        # NamedTemporaryFile creates 0600; a tracked TOML must stay world-readable.
        temporary.chmod(_FILE_MODE)
        temporary.replace(path)
    finally:
        if temporary is not None:
            temporary.unlink(missing_ok=True)


def _without_none(value: object) -> object:
    if isinstance(value, dict):
        return {
            key: _without_none(item) for key, item in value.items() if item is not None
        }
    if isinstance(value, list):
        return [_without_none(item) for item in value]
    return value


def _toml(model: SavedSearchFile) -> bytes:
    payload = cast("dict[str, object]", _without_none(json.loads(codec.encode(model))))
    return (GENERATED_HEADER + "\n" + tomli_w.dumps(payload)).encode()


@dataclass(frozen=True)
class _Recording:
    watches: tuple[Watch, ...]
    results: tuple[Result, ...]
    skipped: int = 0


def _fanout_record(raw: dict[str, object]) -> _Recording:
    query, repo, generated = raw["query"], raw["repo"], raw["generated_at"]
    if not all(isinstance(value, str) for value in (query, generated)) or (
        repo is not None and not isinstance(repo, str)
    ):
        message = "invalid fan-out manifest"
        raise ValueError(message)
    sources = raw["sources"]
    if not isinstance(sources, list):
        message = "invalid sources"
        raise TypeError(message)
    watches: list[Watch] = []
    results: list[Result] = []
    skipped = 0
    for row in sources:
        source = row["source"]
        if source not in _SOURCE_KINDS:
            skipped += 1
            continue
        if not isinstance(repo, str):
            message = "GitHub fan-out manifest requires repo"
            raise TypeError(message)
        kind = _SOURCE_KINDS[source]
        identifier = search_id(kind, repo, cast("str", query))
        watches.append(Watch(identifier, kind, [cast("str", query)], repo=repo))
        items = row["items"]
        # The rerun's vocabulary, so an unchanged watch never reads as a status change.
        status = _FANOUT_STATUS[Status(row["status"])]
        results.append(
            Result(
                identifier,
                cast("str", generated),
                status=str(status),
                # a failed fetch has no count; -1, never a 0 that reads as absence
                count=-1 if status == RerunStatus.error else len(items),
                urls=[item["url"] for item in items],
            )
        )
    return _Recording(tuple(watches), tuple(results), skipped)


def _probe_record(raw: dict[str, object]) -> _Recording:
    if raw.get("kind") != "probe" or not isinstance(raw.get("probes"), list):
        message = "invalid probe manifest"
        raise ValueError(message)
    generated = raw["generated_at"]
    watches: list[Watch] = []
    results: list[Result] = []
    for row in cast("list[dict[str, object]]", raw["probes"]):
        if row.get("kind") != "code-search" or row.get("role") not in set(CodeRole):
            continue
        role, query = CodeRole(row["role"]), cast("str", row["query"])
        identifier = search_id(WatchKind.code, "", query, role)
        watches.append(Watch(identifier, WatchKind.code, [query], role=role))
        count = row.get("count", -1)
        good = (
            row.get("rc") == 0
            and type(count) is int
            and count >= 0
            and not row.get("rate_limited")
            and not row.get("incomplete_results")
        )
        results.append(
            Result(
                identifier,
                cast("str", generated),
                status="ok" if good else "error",
                # a failed, limited or timed-out search has no count, never a 0
                count=count if good else -1,
                # canonical, so a tracked baseline never pins a moving commit ref
                urls=[
                    _canonical(item["html_url"])
                    for item in cast("list[dict[str, str]]", row.get("items", []))
                ],
            )
        )
    return _Recording(tuple(watches), tuple(results))


def _manifest_record(path: Path, *, probe: bool) -> _Recording | None:
    try:
        raw = json.loads(path.read_bytes())
        if not isinstance(raw, dict):
            return None
        recorded = _probe_record(raw) if probe else _fanout_record(raw)
        # Constructors do not validate constraints; decode before accepting a manifest.
        checked = codec.decode(
            codec.encode(
                SavedSearchFile(
                    1, list(recorded.watches), result=list(recorded.results)
                )
            ),
            SavedSearchFile,
        )
        for watch in checked.watch:
            _validate_watch(watch, path)
        for result in _given(checked.result, []):
            _date(result.date_run)
    except OSError, ValueError, TypeError, KeyError, AttributeError:
        return None
    return recorded


def record_main(args: argparse.Namespace, repo_root: Path) -> int:
    """Record real manifests and always print an unambiguous save receipt."""
    path = _resolve(repo_root, args.out)
    receipt: dict[str, object] = {
        "kind": "saved-search-record",
        "out": args.out,
        "path": str(path),
        "written": False,
        "watches": 0,
        "added": 0,
        "updated": 0,
        "skipped_sources": 0,
        "missing": [],
        "reason": None,
    }
    try:
        return _record(args, repo_root, path, receipt)
    except SavedSearchError:
        receipt["reason"] = "invalid saved-search input"
        raise
    except OSError:
        receipt["reason"] = "could not write saved-search file"
        raise
    finally:
        sys.stdout.write(
            "SAVED-SEARCH-JSON "
            + json.dumps(receipt, separators=(",", ":"), sort_keys=True)
            + "\n"
        )


def _record(
    args: argparse.Namespace, root: Path, path: Path, receipt: dict[str, object]
) -> int:
    if path.exists() and path.read_text(encoding="utf-8").splitlines()[:1] != [
        GENERATED_HEADER
    ]:
        receipt["reason"] = "refused: not a generated file"
        return 1
    previous = load(path) if path.exists() else SavedSearchFile(1, [])
    watches = {watch.id: watch for watch in previous.watch}
    results = {result.watch_id: result for result in _given(previous.result, [])}
    incoming: dict[str, Watch] = {}
    baselines: dict[str, Result] = {}
    missing: list[str] = []
    skipped = 0
    for probe, paths in ((False, args.fanout_manifest), (True, args.probe_manifest)):
        for value in paths:
            recorded = _manifest_record(_resolve(root, value), probe=probe)
            if recorded is None:
                missing.append(value)
                continue
            incoming.update((watch.id, watch) for watch in recorded.watches)
            baselines.update((result.watch_id, result) for result in recorded.results)
            skipped += recorded.skipped
    for value in args.code_search:
        role, sep, query = value.partition("=")
        if not sep or role not in set(CodeRole) or not query:
            raise _invalid(path, "<import>", "--code-search ROLE=QUERY")
        identifier = search_id(WatchKind.code, "", query, role)
        incoming[identifier] = Watch(
            identifier, WatchKind.code, [query], role=CodeRole(role)
        )
    receipt.update(missing=missing, skipped_sources=skipped)
    receipt.update(
        added=len(incoming.keys() - watches.keys()),
        updated=len(incoming.keys() & watches.keys()),
    )
    watches.update(incoming)
    results.update(baselines)
    receipt["watches"] = len(watches)
    if not watches:
        receipt["reason"] = "no watches"
        return 1
    if not incoming:
        # Rewriting an existing file with nothing from THIS run would report a save
        # that saved nothing (cold review F8).
        receipt["reason"] = "no readable input from this run"
        return 1
    model = SavedSearchFile(
        1,
        list(watches.values()),
        result=list(results.values()),
        question=previous.question if args.question is None else args.question,
        origin=previous.origin if args.origin is None else args.origin,
    )
    _atomic_write(path, _toml(model))
    receipt["written"] = True
    for watch in model.watch:
        sys.stdout.write(f"{watch.id}  {watch.kind}  {'; '.join(watch.queries)}\n")
    return 0


def shape_of(query: str) -> str:
    """Port the workflow's qualifier, boolean and parenthesis shape exactly."""
    tokens: list[str] = []
    for token in query.split():
        if re.match(r"^-?[A-Za-z_]+:\S", token):
            tokens.append(token.lower())
        elif token in {"OR", "AND", "NOT"}:
            tokens.append(token)
        elif "(" in token or ")" in token:
            tokens.append("()")
    return " ".join(sorted(tokens))


def _absent(query: str) -> str:
    qualifiers = [
        token.lower().replace("(", "").replace(")", "")
        for token in query.split()
        if re.match(r"^-?[A-Za-z_]+:\S", token)
    ]
    nonce = "zz" + secrets.token_hex(6)
    return " ".join([f'"{nonce}"', *qualifiers])


@dataclass
class _PacedRunner:
    runner: Runner
    timing: ProbeTiming
    searched: bool = False

    def __call__(
        self, argv: list[str], *, timeout: float, env: dict[str, str]
    ) -> subprocess.CompletedProcess[bytes]:
        if "search/code" in argv:
            if self.searched:
                self.timing.sleep(_CODE_PACE)
            self.searched = True
        return self.runner(argv, timeout=timeout, env=env)


@dataclass(frozen=True)
class _Answer:
    count: int
    status: RerunStatus
    items: tuple[dict[str, object], ...]
    rc: int
    reason: str | None = None
    complete: bool = False


def _direct(
    query: str,
    watch: Watch,
    boundaries: _ProbeBoundaries,
    timeout: float,
    *,
    page: int = 0,
) -> _Answer:
    """One search call; `page` >= 1 asks for that full page of `_PAGE_SIZE` hits."""
    limit = _PAGE_SIZE if page else _given(watch.limit, 10)
    if watch.kind == WatchKind.code:
        tail = [
            "-X",
            "GET",
            "search/code",
            "-f",
            f"q={query}",
            "-f",
            f"per_page={limit}",
        ]
        if page > 1:
            tail += ["-f", f"page={page}"]
    elif watch.kind == WatchKind.issues:
        tail = [f"search/issues?q={quote_plus(query)}&per_page={limit}"]
    else:
        tail = [
            "graphql",
            "-f",
            f"query={_GITHUB_QUERY}",
            "-f",
            f"searchQuery={query}",
            "-F",
            f"limit={limit}",
        ]
    response = _gh_include(tail, boundaries=boundaries, timeout=timeout)
    if response.rate_limited:
        return _Answer(-1, RerunStatus.rate_limited, (), response.rc, "rate limited")
    body = response.body
    if response.rc != 0 or response.status >= _HTTP_ERROR or not isinstance(body, dict):
        return _Answer(-1, RerunStatus.error, (), response.rc, "search failed")
    if body.get("incomplete_results") is True:
        return _Answer(
            -1, RerunStatus.incomplete, (), response.rc, "incomplete results"
        )
    if watch.kind == WatchKind.discussions:
        data = body.get("data")
        search = data.get("search") if isinstance(data, dict) else None
        items = search.get("nodes") if isinstance(search, dict) else None
        count = len(items) if isinstance(items, list) and not body.get("errors") else -1
    else:
        count, items = body.get("total_count"), body.get("items")
    if type(count) is not int or count < 0 or not isinstance(items, list):
        return _Answer(
            -1, RerunStatus.error, (), response.rc, "invalid search response"
        )
    return _Answer(
        count,
        RerunStatus.ok,
        tuple(item for item in items[:limit] if isinstance(item, dict)),
        response.rc,
    )


def _canonical(url: str) -> str:
    """Pin a code-search blob URL to HEAD so a diff keys on repo + path.

    search/code returns `/blob/<commit sha>/<path>`, and the sha moves with every
    push, so without this every rerun reported every hit as NEW and its previous
    URL as GONE (measured live on the IWYU file, 2026-10-03). Issue, PR and
    release URLs carry no `/blob/` and pass through unchanged.
    """
    return _BLOB_REF.sub(r"\1HEAD/", url)


def _collect_all(
    query: str, watch: Watch, boundaries: _ProbeBoundaries, timeout: float
) -> _Answer:
    """Page through EVERY hit (up to the REST cap) so NEW means new to the index.

    Code search ranks by best match and has no date sort or qualifier
    (`sort=indexed` is ignored; measured 2026-10-03, research report
    saved-searches-newer-examples-research-2026-10-03.md), so a top-N window
    diffs a RANKING: a new example ranked 50th never shows as NEW. One failed,
    limited or timed-out page fails the whole run — a partial set would report
    false GONE rows. The count is the number of keys collected; `total_count`
    moved 125 -> 141 between two calls seconds apart, so it is not used.
    """
    seen: dict[str, dict[str, object]] = {}
    for page in range(1, _RESULT_CAP // _PAGE_SIZE + 1):
        answer = _direct(query, watch, boundaries, timeout, page=page)
        if answer.status != RerunStatus.ok:
            return answer
        # Every page, not just the first: a total that grows past the cap mid-run
        # would otherwise end as a "complete" set missing hits (codex lens P2).
        if answer.count > _RESULT_CAP:
            return _Answer(
                -1,
                RerunStatus.uncollectable,
                (),
                answer.rc,
                f"{answer.count} hits exceed the {_RESULT_CAP}-result cap; "
                "split the query (for example by size: ranges)",
            )
        for item in answer.items:
            url = item.get("html_url")
            if isinstance(url, str):
                seen.setdefault(_canonical(url), item)
        if len(answer.items) < _PAGE_SIZE:
            break
    return _Answer(len(seen), RerunStatus.ok, tuple(seen.values()), 0, complete=True)


def _search_code(
    query: str, watch: Watch, boundaries: _ProbeBoundaries, timeout: float
) -> tuple[_Answer, int | None]:
    """Run one code query in its collect mode and confirm its top `limit` hits."""
    if collect_mode(watch) == Collect.all:
        answer = _collect_all(query, watch, boundaries, timeout)
    else:
        answer = _direct(query, watch, boundaries, timeout)
    # grep confirmation re-fetches each file; bound it to `limit` items in every
    # mode, so `collect = "all"` adds search pages, not hundreds of raw fetches.
    sample = replace(answer, items=answer.items[: _given(watch.limit, 10)])
    confirmed = _confirmed(
        sample,
        _given(watch.grep, ""),
        _given(watch.path_grep, ""),
        boundaries.runner,
        timeout,
    )
    return answer, confirmed


def _urls(answer: _Answer) -> list[str]:
    return [
        _canonical(url)
        for item in answer.items
        if isinstance(url := item.get("html_url") or item.get("url"), str)
    ]


def _confirmed(
    answer: _Answer,
    grep: str,
    path_grep: str,
    runner: Runner,
    timeout: float,
) -> int | None:
    if not grep and not path_grep:
        return None
    count = 0
    for item in answer.items:
        url = item.get("url")
        if not isinstance(url, str):
            continue
        try:
            fetched = runner(
                ["gh", "api", url, "-H", "Accept: application/vnd.github.raw"],
                timeout=timeout,
                env=_gh_env(),
            )
        except OSError, subprocess.TimeoutExpired:
            continue
        if (
            fetched.returncode == 0
            and (
                not grep
                or re.search(
                    grep, (fetched.stdout or b"").decode(errors="replace"), re.MULTILINE
                )
            )
            and (not path_grep or re.search(path_grep, str(item.get("path", ""))))
        ):
            count += 1
    return count


def _control(role: str, query: str, answer: _Answer) -> SearchControl:
    return SearchControl(role, query, answer.count, answer.rc, answer.status)


def _draft_armed(
    watch: Watch,
    boundaries: _ProbeBoundaries,
    timeout: float,
    controls: list[SearchControl],
) -> bool | None:
    """Arm a watch by its own draft controls; None = it has none.

    A code watch may carry `control_hit` alone: its negative arm is then the
    fresh per-shape known-absent the caller already runs, so the caller ANDs
    that in. Any other kind has no per-shape absent, so a lone `control_hit`
    cannot arm it (False), and a lone `control_absent` arms nothing anywhere.
    """
    hit, absent = _given(watch.control_hit, ""), _given(watch.control_absent, "")
    if not hit and not absent:
        return None
    if not hit or (not absent and watch.kind != WatchKind.code):
        return False
    positive = _direct(hit, watch, boundaries, timeout)
    controls.append(_control("must-hit", hit, positive))
    confirmed = _confirmed(
        positive,
        _given(watch.control_hit_grep, ""),
        _given(watch.control_hit_path_grep, ""),
        boundaries.runner,
        timeout,
    )
    hit_ok = (
        positive.status == RerunStatus.ok
        and positive.count > 0
        and (confirmed is None or confirmed > 0)
    )
    if not absent:
        return hit_ok
    negative_query = absent.replace("{nonce}", "zz" + secrets.token_hex(6))
    negative = _direct(negative_query, watch, boundaries, timeout)
    controls.append(_control("known-absent", negative_query, negative))
    return hit_ok and negative.status == RerunStatus.ok and negative.count == 0


def _zero_armed(
    watch: Watch,
    query: str,
    *,
    draft: bool | None,
    hits: set[str],
    negatives: dict[str, bool],
) -> bool:
    """Decide whether a code 0 is evidence: both arms must have answered."""
    shape = shape_of(query)
    if draft is None:
        return shape in hits and negatives.get(shape, False)
    if draft and not _given(watch.control_absent, ""):
        # a lone control_hit borrows the shape's fresh known-absent
        return negatives.get(shape, False)
    return draft


def _run_code(
    watches: list[Watch], boundaries: _ProbeBoundaries, timeout: float
) -> tuple[list[WatchRun], list[SearchControl], bool]:
    controls: list[SearchControl] = []
    health_watch = Watch("health", WatchKind.code, [_HEALTH])
    health = _direct(_HEALTH, health_watch, boundaries, timeout)
    controls.append(_control("health", _HEALTH, health))
    healthy = health.status == RerunStatus.ok and health.count > 0
    shapes = {
        shape_of(query): query
        for watch in watches
        if _given(watch.role, CodeRole.query) == CodeRole.query
        for query in watch.queries
    }
    negatives: dict[str, bool] = {}
    for shape, query in shapes.items():
        absent = _absent(query)
        answer = _direct(absent, health_watch, boundaries, timeout)
        controls.append(_control("known-absent", absent, answer))
        negatives[shape] = answer.status == RerunStatus.ok and answer.count == 0
    answers: list[tuple[Watch, str, _Answer, int | None]] = []
    drafts: dict[str, bool | None] = {}
    hits: set[str] = set()
    for watch in watches:
        drafts[watch.id] = _draft_armed(watch, boundaries, timeout, controls)
        for query in watch.queries:
            answer, confirmed = _search_code(query, watch, boundaries, timeout)
            answers.append((watch, query, answer, confirmed))
            if _given(watch.role, CodeRole.query) == CodeRole.must_hit:
                controls.append(_control("must-hit", query, answer))
                if answer.status == RerunStatus.ok and answer.count > 0:
                    hits.add(shape_of(query))
    runs: list[WatchRun] = []
    for watch, query, answer, confirmed in answers:
        status, reason = answer.status, answer.reason
        if not healthy:
            status, reason = RerunStatus.error, "code search unhealthy"
        elif answer.count == 0 and status == RerunStatus.ok:
            armed = _zero_armed(
                watch, query, draft=drafts[watch.id], hits=hits, negatives=negatives
            )
            status = RerunStatus.empty_verified if armed else RerunStatus.empty_unarmed
            reason = None if armed else "controls did not arm this search"
        runs.append(
            WatchRun(
                watch.id,
                Kind.code,
                query,
                _given(watch.repo, "") or None,
                status,
                answer.count,
                _urls(answer),
                confirmed,
                reason,
                complete=True if answer.complete else UNSET,
            )
        )
    failed = (
        not healthy
        or not all(negatives.values())
        or any(value is False for value in drafts.values())
    )
    failed = failed or any(control.status != RerunStatus.ok for control in controls)
    return runs, controls, failed


def _run_other(
    watch: Watch, boundaries: _ProbeBoundaries, timeout: float
) -> tuple[list[WatchRun], list[SearchControl], bool]:
    controls: list[SearchControl] = []
    repo = _given(watch.repo, "")
    armed = None if repo else _draft_armed(watch, boundaries, timeout, controls)
    runs: list[WatchRun] = []
    for query in watch.queries:
        if repo:
            source = next(
                source for source, kind in _SOURCE_KINDS.items() if kind == watch.kind
            )
            result = fan_out(
                FanoutRequest(query, repo, (source,), _given(watch.limit, 10), timeout),
                runner=boundaries.runner,
            )[0]
            status = _FANOUT_STATUS[result.status]
            # a failed or skipped fetch has no count: -1, never a measured 0
            count = -1 if status == RerunStatus.error else len(result.items)
            urls = [item.url for item in result.items]
            reason = (
                None
                if status in {RerunStatus.ok, RerunStatus.empty_verified}
                else "fan-out did not verify this search"
            )
        else:
            answer = _direct(query, watch, boundaries, timeout)
            count, status, urls, reason = (
                answer.count,
                answer.status,
                _urls(answer),
                answer.reason,
            )
            if count == 0 and status == RerunStatus.ok:
                status = (
                    RerunStatus.empty_verified if armed else RerunStatus.empty_unarmed
                )
                reason = None if armed else "draft controls did not arm this search"
        runs.append(
            WatchRun(
                watch.id,
                Kind(watch.kind),
                query,
                repo or None,
                status,
                count,
                urls,
                None,
                reason,
            )
        )
    return runs, controls, armed is False


@dataclass(frozen=True)
class _Previous:
    count: int | None
    urls: tuple[str, ...]
    status: str | None
    complete: bool = False


def _snapshot_paths(directory: Path, file: Path) -> list[Path]:
    return sorted((directory / file.stem).glob("*.json"))


def _previous(
    file: Path, model: SavedSearchFile, directory: Path, now: datetime
) -> tuple[str, dict[tuple[str, str], _Previous]]:
    """Pick the previous observation PER (watch id, query), newest first.

    Chosen per file, a `rerun --id X` made the next full rerun show every other
    watch as a first run with all URLs NEW, and a watch added by a later `record`
    lost its baseline the same way (cold review M2, 2026-10-03). So each key takes
    its newest snapshot entry and falls back to its own TOML baseline.
    """
    newest: dict[str, Result] = {}
    for result in _given(model.result, []):
        if result.watch_id not in newest or _date(result.date_run) > _date(
            newest[result.watch_id].date_run
        ):
            newest[result.watch_id] = result
    chosen: dict[tuple[str, str], _Previous] = {
        (watch.id, query): _Previous(
            _given(result.count, _given(result.total_count, None)),
            tuple(_given(result.urls, [])),
            _status_word(_given(result.status, None)),
        )
        for watch in model.watch
        if (result := newest.get(watch.id)) is not None
        for query in watch.queries
    }
    candidates: list[tuple[datetime, Path, SavedSearchSnapshot]] = []
    for path in _snapshot_paths(directory, file):
        try:
            snapshot = codec.decode(path.read_bytes(), SavedSearchSnapshot)
            when = _date(snapshot.generated_at)
        except OSError, ValueError:
            raise _invalid(path, "<snapshot>", "snapshot") from None
        if snapshot.file == str(file) and when < now:
            candidates.append((when, path, snapshot))
    # Oldest first, so a newer snapshot's entry overwrites an older one per key.
    # Only ANSWERED runs overwrite: a failed run between {A} and {A,B} would
    # otherwise become the previous run and hide B as NEW for good (codex lens P2).
    for _, _, snapshot in sorted(candidates, key=lambda item: item[0]):
        chosen.update(
            (
                (run.id, run.query),
                _Previous(run.count, tuple(run.urls), run.status, run.complete is True),
            )
            for run in snapshot.watches
            if str(run.status) in _COMPARABLE
        )
    if not candidates:
        return "baseline", chosen
    newest_path = max(candidates, key=lambda item: item[0])[1]
    return (
        f"snapshot {newest_path} (per watch, else older snapshot or baseline)",
        chosen,
    )


def _status_word(status: str | None) -> str | None:
    """Read a baseline status in the rerun's vocabulary (older files use fan-out's)."""
    if status is None:
        return None
    try:
        return str(_FANOUT_STATUS[Status(status)])
    except ValueError:
        return status


def _cell(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ").replace("\r", " ")


def _row(run: WatchRun, before: _Previous | None) -> list[str]:
    """One diff row; NEW/GONE only when both runs can be compared."""
    complete = run.complete is True
    # A baseline or older snapshot may hold sha-pinned blob URLs.
    old_urls = {_canonical(url) for url in before.urls} if before else set()
    old_count = before.count if before and before.count is not None else "n/a"
    counts = f"{old_count} → {run.count}" if before else f"first run → {run.count}"
    if complete:
        counts += " (all collected)"
    elif run.count > len(run.urls):
        # Only the top `limit` best-match hits are kept: a NEW/GONE here can be
        # ranking churn, not a new or vanished example.
        counts += f" (top {len(run.urls)} of {run.count})"
    status = str(run.status)
    if before and before.status is not None and before.status != run.status:
        status += f" (was {before.status})"
    if run.reason:
        status += f": {run.reason}"
    # A run that failed or whose 0 is unarmed returned no URLs, so diffing it
    # would list every previous URL as GONE (cold review M1). Diff only two
    # answered runs; a baseline with no recorded status counts as answered.
    answered = str(run.status) in _COMPARABLE and (
        before is None or before.status is None or before.status in _COMPARABLE
    )
    if not answered:
        return [run.id, run.kind, run.query, counts, status, "n/a", "n/a"]
    if complete and before is not None and not before.complete:
        # The previous run saw only a top-N window: every hit outside it would
        # read as NEW. The NEXT full collection diffs set against set.
        return [
            run.id,
            run.kind,
            run.query,
            counts,
            status,
            "n/a (first full collection)",
            "n/a (first full collection)",
        ]
    new = ", ".join(sorted(set(run.urls) - old_urls))
    gone = ", ".join(sorted(old_urls - set(run.urls)))
    return [run.id, run.kind, run.query, counts, status, new, gone]


def _report(
    snapshot: SavedSearchSnapshot,
    source: str,
    previous: dict[tuple[str, str], _Previous],
) -> str:
    totals = Counter(run.status for run in snapshot.watches)
    lines = [
        f"# Saved searches: {snapshot.file}",
        f"Run: {snapshot.generated_at}",
        f"Previous: {source}",
        "Totals: "
        + ", ".join(f"{status}={count}" for status, count in sorted(totals.items())),
        "",
        "| id | kind | query | count | status | NEW | GONE |",
        "|---|---|---|---|---|---|---|",
    ]
    for run in snapshot.watches:
        cells = _row(run, previous.get((run.id, run.query)))
        lines.append("| " + " | ".join(_cell(cell) for cell in cells) + " |")
    # Without this a run that exits 1 on a failed control printed no reason.
    if snapshot.controls:
        lines += [
            "",
            "## Controls",
            "",
            "| role | query | count | status |",
            "|---|---|---|---|",
        ]
        lines += [
            "| "
            + " | ".join(_cell(cell) for cell in (c.role, c.query, c.count, c.status))
            + " |"
            for c in snapshot.controls
        ]
    return "\n".join(lines) + "\n"


def rerun_main(
    args: argparse.Namespace, repo_root: Path, *, runner: Runner, timing: ProbeTiming
) -> int:
    """Rerun selected watches serially, then write a snapshot and markdown diff."""
    file = _resolve(repo_root, args.file)
    model = load(file)
    unknown = set(args.id) - {watch.id for watch in model.watch}
    if unknown:
        raise _invalid(file, ", ".join(sorted(unknown)), "--id")
    if args.timeout <= 0:
        raise _invalid(file, "<file>", "--timeout")
    if args.report and _resolve(repo_root, args.report) == file:
        raise _invalid(file, "<file>", "--report (would overwrite saved-search file)")
    selected = [watch for watch in model.watch if not args.id or watch.id in args.id]
    now = datetime.fromtimestamp(timing.clock(), UTC)
    directory = _resolve(repo_root, args.snapshot_dir)
    source, previous = _previous(file, model, directory, now)
    paced = _PacedRunner(runner, timing)
    boundaries = _ProbeBoundaries(paced, timing.sleep, timing.clock)
    watches, controls, failed = [], [], False
    code = [watch for watch in selected if watch.kind == WatchKind.code]
    if code:
        watches, controls, failed = _run_code(code, boundaries, args.timeout)
    for watch in selected:
        if watch.kind != WatchKind.code:
            runs, checks, failure = _run_other(watch, boundaries, args.timeout)
            watches.extend(runs)
            controls.extend(checks)
            failed = failed or failure
    snapshot = SavedSearchSnapshot(str(file), now.isoformat(), watches, controls)
    target = directory / file.stem / f"{now:%Y%m%dT%H%M%SZ}.json"
    _atomic_write(target, codec.encode(snapshot))
    report = _report(snapshot, source, previous)
    if args.report:
        _atomic_write(_resolve(repo_root, args.report), report.encode())
    sys.stdout.write(report)
    return int(
        failed
        or any(
            run.status not in {RerunStatus.ok, RerunStatus.empty_verified}
            for run in watches
        )
    )


def status_main(
    args: argparse.Namespace, repo_root: Path, *, timing: ProbeTiming
) -> int:
    """Report baseline/snapshot freshness without changing any saved file."""
    files: list[Path] = []
    for value in args.paths or ["docs/research/saved-searches"]:
        path = _resolve(repo_root, value)
        files.extend(sorted(path.glob("*.toml")) if path.is_dir() else [path])
    sys.stdout.write("| file | watches | baseline | snapshot | age days | state |\n")
    sys.stdout.write("|---|---|---|---|---|---|\n")
    now = datetime.fromtimestamp(timing.clock(), UTC)
    for file in files:
        model = load(file)
        baseline = max(
            (_date(result.date_run) for result in _given(model.result, [])),
            default=None,
        )
        snapshots = []
        for path in _snapshot_paths(_resolve(repo_root, _SNAPSHOT_DIR), file):
            try:
                snapshot = codec.decode(path.read_bytes(), SavedSearchSnapshot)
                if snapshot.file == str(file):
                    snapshots.append(_date(snapshot.generated_at))
            except OSError, ValueError:
                raise _invalid(path, "<snapshot>", "snapshot") from None
        latest = max(snapshots, default=None)
        newest = latest or baseline
        age = (
            max(0.0, (now - newest).total_seconds() / _SECONDS_PER_DAY)
            if newest
            else None
        )
        cadence = min(
            (
                1 if _given(watch.cadence, Cadence.weekly) == Cadence.daily else 7
                for watch in model.watch
            ),
            default=7,
        )
        state = "STALE" if age is None or age > cadence else "fresh"
        cells = [
            file,
            len(model.watch),
            baseline.isoformat() if baseline else "never",
            latest.isoformat() if latest else "never",
            f"{age:.2f}" if age is not None else "n/a",
            state,
        ]
        sys.stdout.write("| " + " | ".join(_cell(cell) for cell in cells) + " |\n")
    return 0


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    subcommands = parser.add_subparsers(dest="command", required=True)
    record = subcommands.add_parser("record")
    record.add_argument("--out", required=True)
    record.add_argument("--question")
    record.add_argument("--origin")
    record.add_argument("--fanout-manifest", action="append", default=[])
    record.add_argument("--probe-manifest", action="append", default=[])
    record.add_argument("--code-search", action="append", default=[])
    rerun = subcommands.add_parser("rerun")
    rerun.add_argument("file")
    rerun.add_argument("--id", action="append", default=[])
    rerun.add_argument("--snapshot-dir", default=_SNAPSHOT_DIR)
    rerun.add_argument("--report")
    rerun.add_argument("--timeout", type=float, default=60.0)
    status = subcommands.add_parser("status")
    status.add_argument("paths", nargs="*")
    return parser


def main(
    argv: list[str],
    repo_root: Path,
    *,
    runner: Runner = default_runner,
    timing: ProbeTiming = _REAL_TIMING,
) -> int:
    """Dispatch the CLI through the existing injected subprocess/time boundary."""
    try:
        args = _parser().parse_args(argv)
    except SystemExit as error:
        return error.code if isinstance(error.code, int) else 2
    try:
        if args.command == "record":
            return record_main(args, repo_root)
        if args.command == "rerun":
            return rerun_main(args, repo_root, runner=runner, timing=timing)
        return status_main(args, repo_root, timing=timing)
    except SavedSearchError as error:
        sys.stderr.write(f"{error}\n")
        return 2
    except OSError:
        sys.stderr.write("saved searches: filesystem operation failed\n")
        return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:], _repo_root()))
