#!/usr/bin/env bash
# devcontainer-smoke.sh — Tier 1/2/3 smoke checks run INSIDE the devcontainer.
#
# Invocation modes:
#   - postCreateCommand (devcontainer.json): runs automatically on first create
#   - Manual: `devcontainer exec --workspace-folder . scripts/devcontainer-smoke.sh`
#
# Tiers (per ralplan-consensus-devcontainer-build-mise-chezmoi-resync §5):
#   Tier 1 — Tools+hk:      mise ls; which clang++ python uv hk; hk run pre-commit --all
#   Tier 2 — Python+mounts: uv pytest 190/190; stat ~/.ssh ~/.claude /workspaces/${ws}
#   Tier 3 — Sanitizers+lifecycle: clang++ asan+ubsan; mise-user volume owner; github ssh
#
# Tier 4 (CLion remote toolchain) is manual and out of scope here.
set -euo pipefail

echo "[devcontainer-smoke][start]"

WORKSPACE_FOLDER="${WORKSPACE_FOLDER:-/workspaces/$(basename "$PWD")}"

echo "::group::Tier 1 — tools + hk"
echo "[tier1] image identity + exact tool-set (python-generated shared core)"
# #223: the image-identity hashes and the exact (tool, backend, version)
# assertion are generated by python (dotfiles_setup.image.build_tier1_script,
# emitted by `image smoke-script --tier 1`) and eval'd here, so THIS
# in-container path and the CI no-mount smoke run BYTE-IDENTICAL tier-1 logic —
# the two smoke paths cannot diverge. The generator injects merge-base-aware
# expected hashes/tools: a branch that CHANGES an image build input can never
# have a LOCAL base built from it (the new base is built by that branch's own
# PR CI), so the local base is compared against the MERGE-BASE content; branch
# identity/tool bumps are validated by the PR CI build+smoke instead. It reads
# $MISE_SYSTEM_CONFIG_FILE for identity (#148) and diffs the system/shared/
# runtime tiers for the tool-set (#160). Run under `bash -lc` so mise is
# activated and jq is on PATH, exactly as the CI smoke's `/bin/bash -lc`.
tier1_core="$(cd "${WORKSPACE_FOLDER}" && uv run --project python dotfiles-setup image smoke-script --tier 1)"
bash -lc "$tier1_core"
# hk + compiler presence stay in bash: `hk run pre-commit --all` lints the
# MOUNTED workspace, so it is inherently mount-dependent and cannot run in the
# CI no-mount smoke (which has no repo files to lint). Uses the image-only hk
# config at /etc/hk/hk.pkl (the project ./hk.pkl has host-only steps —
# docker_bake_check -> @devcontainers/cli, agnix, etc.); HK_FILE is hk's
# built-in config-file override (per hk env_variables docs).
which clang++ python uv hk
HK_FILE=/etc/hk/hk.pkl hk run pre-commit --all
echo "::endgroup::"

echo "::group::Tier 2 — pytest + mounts + secrets"
uv run --project python pytest tests/ -x -q
stat "${HOME}/.ssh"
stat "${WORKSPACE_FOLDER}"

echo "[tier2] Doppler secrets injection"
# Verify doppler secrets were injected via --env-file. DOPPLER_PROJECT and
# DOPPLER_CONFIG are always present in any doppler download; use them as
# canary keys. Count total doppler-sourced env vars as a sanity check.
if [ -z "${DOPPLER_PROJECT:-}" ] || [ -z "${DOPPLER_CONFIG:-}" ]; then
  echo "  FAIL: DOPPLER_PROJECT or DOPPLER_CONFIG not set (doppler secrets not injected — is doppler authenticated on the host?)" >&2
  exit 1
fi
doppler_count=$(env | grep -cE "^(DOPPLER_PROJECT|DOPPLER_CONFIG|DOPPLER_ENVIRONMENT|EXA_API_KEY|GITHUB_TOKEN|BRAVE_API_KEY|GEMINI_API_KEY)=" || true)
if [ "${doppler_count}" -lt 3 ]; then
  echo "  FAIL: only ${doppler_count} doppler canary keys found (expected >= 3)" >&2
  exit 1
fi
echo "  OK: doppler secrets injected (${doppler_count} canary keys, project=${DOPPLER_PROJECT}, config=${DOPPLER_CONFIG})"
echo "::endgroup::"

echo "::group::Tier 3 — sanitizers + lifecycle"
td=$(mktemp -d)
cat > "$td/hello.cc" <<'CC'
#include <cstdio>
int main() { std::puts("ok"); return 0; }
CC
clang++ -fsanitize=address,undefined -O1 -g "$td/hello.cc" -o "$td/hello"
"$td/hello"
rm -rf "$td"

echo "[tier3] reflection compilers — ref pin + functional"
# The sanitizer block above uses the conda clang++ on PATH; it never touches
# the P2996 reflection compiler. Assert the clang-p2996 build (a) is a real
# bloomberg/clang-p2996 build and (b) its embedded source commit matches the
# CLANG_P2996_REF pinned in docker-bake.hcl — without this a stale/wrong-ref
# (or missing) reflection compiler is a silent false positive. Then compile a
# std::meta program with both reflection compilers (-fsyntax-only; the
# static_assert forces compile-time reflection evaluation, and clang-p2996's
# -stdlib=libc++ binary can't be run — libc++.so.1 is off the loader path).
test -x /opt/clang-p2996/bin/clang++ || { echo "  FAIL: /opt/clang-p2996/bin/clang++ missing" >&2; exit 1; }
test -x /opt/gcc-latest/bin/g++ || { echo "  FAIL: /opt/gcc-latest/bin/g++ missing" >&2; exit 1; }
expected_ref="$(grep -A2 'CLANG_P2996_REF' "${WORKSPACE_FOLDER}/docker-bake.hcl" | grep -oiE '[0-9a-f]{40}' | head -1)"
[ -n "${expected_ref}" ] || { echo "  FAIL: could not parse CLANG_P2996_REF from docker-bake.hcl" >&2; exit 1; }
p2996_version="$(/opt/clang-p2996/bin/clang --version)"
echo "${p2996_version}" | grep -q 'bloomberg/clang-p2996' || { echo "  FAIL: /opt/clang-p2996 clang is not a bloomberg/clang-p2996 build" >&2; exit 1; }
actual_ref="$(echo "${p2996_version}" | grep -oiE '[0-9a-f]{40}' | head -1)"
if [ "${actual_ref}" != "${expected_ref}" ]; then
	echo "  FAIL: clang-p2996 built from ${actual_ref} but docker-bake.hcl pins ${expected_ref}" >&2
	exit 1
fi
echo "  OK: clang-p2996 ref ${actual_ref} matches docker-bake.hcl"
# Gap C (#141): link + RUN, not just -fsyntax-only. The static_assert forces
# compile-time reflection evaluation; the RUN proves the emitted binary
# executes. clang-p2996's -stdlib=libc++ binary needs libc++.so.1, which is off
# the default loader path, so bake an rpath at the discovered in-image libc++
# dir (link-flag-only — no Dockerfile change, no cold rebuild). A p2996 libc++
# binary runs under Rosetta/QEMU (verified #141), so no emulation gate needed.
p2996_libcxx_so="$(find /opt/clang-p2996/lib -name 'libc++.so.1' 2>/dev/null | head -n1)"
[ -n "${p2996_libcxx_so}" ] || { echo "  FAIL: clang-p2996 libc++.so.1 not found in image" >&2; exit 1; }
p2996_libcxx_dir="$(dirname "${p2996_libcxx_so}")"
rd="$(mktemp -d)"
cat >"${rd}/refl.cpp" <<'CPP'
#include <meta>
#include <iostream>
enum class Color { Red, Green, Blue };
consteval int count_enumerators() {
  return static_cast<int>(enumerators_of(^^Color).size());
}
static_assert(count_enumerators() == 3);
int main() {
  int n = count_enumerators();
  std::cout << "reflection enumerators=" << n << std::endl;
  return n == 3 ? 0 : 1;
}
CPP
/opt/gcc-latest/bin/g++ -std=c++26 -freflection "${rd}/refl.cpp" -o "${rd}/refl-gcc" || { echo "  FAIL: gcc-latest reflection link failed" >&2; exit 1; }
"${rd}/refl-gcc" || { echo "  FAIL: gcc-latest reflection binary did not run to return 0" >&2; exit 1; }
/opt/clang-p2996/bin/clang++ -std=c++2c -freflection -freflection-latest -fexpansion-statements -stdlib=libc++ -Wl,-rpath,"${p2996_libcxx_dir}" "${rd}/refl.cpp" -o "${rd}/refl-clang" || { echo "  FAIL: clang-p2996 reflection link failed" >&2; exit 1; }
"${rd}/refl-clang" || { echo "  FAIL: clang-p2996 reflection binary did not run to return 0" >&2; exit 1; }
rm -rf "${rd}"
echo "  OK: both reflection compilers link + run a std::meta program"

echo "[tier3] home volume ownership + seed survivors"
# v6 single-home-volume contract: the whole /home/${USER} dir is a
# persistent named volume. Assert (a) mise install dir is user-owned
# (same invariant as pre-v6), and (b) the chezmoi-managed shell files,
# .ssh, and mise install dir were all seeded correctly on first create.
owner="$(stat -c '%U' "${HOME}/.local/share/mise")"
if [ "${owner}" = "${USER}" ]; then
  echo "  OK: ${HOME}/.local/share/mise owned by ${USER}"
else
  echo "  FAIL: ${HOME}/.local/share/mise owned by ${owner}, expected ${USER}" >&2
  exit 1
fi

for f in "${HOME}/.bashrc" "${HOME}/.zshrc" "${HOME}/.profile"; do
  if [ -e "$f" ]; then
    echo "  OK: ${f} exists"
  else
    echo "  FAIL: ${f} missing — chezmoi init may have wiped seeded files" >&2
    exit 1
  fi
done
for d in "${HOME}/.ssh" "${HOME}/.local/share/mise" "${HOME}/.local/tmp"; do
  if [ -d "$d" ]; then
    echo "  OK: ${d} exists"
  else
    echo "  FAIL: ${d} missing" >&2
    exit 1
  fi
done

# TMPDIR must be set to the home-volume path so tools that respect
# $TMPDIR land on the persistent volume, not the ephemeral overlay.
expected_tmpdir="${HOME}/.local/tmp"
if [ "${TMPDIR:-}" != "${expected_tmpdir}" ]; then
  echo "  FAIL: TMPDIR=${TMPDIR:-<unset>}, expected ${expected_tmpdir}" >&2
  exit 1
fi
echo "  OK: TMPDIR=${TMPDIR}"

echo "[tier3] SSH agent forwarding + github auth"
# Real end-to-end SSH auth via Docker Desktop's native magic socket at
# /run/host-services/ssh-auth.sock (see .omc/research/research-20260409c-dockerdesktop-ssh/).
# Runtime-pinned to Docker Desktop — Colima has no equivalent; issue #78 tracks
# eventual Colima replication.
expected_sock="/run/host-services/ssh-auth.sock"
if [ "${SSH_AUTH_SOCK:-}" != "${expected_sock}" ]; then
  echo "  FAIL: SSH_AUTH_SOCK=${SSH_AUTH_SOCK:-<unset>}, expected ${expected_sock}" >&2
  exit 1
fi
if [ ! -S "${expected_sock}" ]; then
  echo "  FAIL: ${expected_sock} is not a socket (Docker Desktop magic mount missing — are you on Docker Desktop? 'docker context ls' should show desktop-linux *)" >&2
  exit 1
fi
if ! ssh-add -L 2>/dev/null | grep -q '^ssh-'; then
  echo "  FAIL: ssh-add -L shows no identities (host ssh-agent empty? run 'ssh-add ~/.ssh/id_*' on the Mac)" >&2
  ssh-add -L 2>&1 | awk '{print "    " $0}' >&2 || true
  exit 1
fi
ssh_out=$(ssh -o BatchMode=yes -o ConnectTimeout=10 -T git@github.com 2>&1 || true)
if echo "${ssh_out}" | grep -q "successfully authenticated"; then
  echo "  OK: github ssh full auth via /run/host-services/ssh-auth.sock"
else
  echo "  FAIL: github ssh did not reach successful auth" >&2
  echo "${ssh_out}" | awk '{print "    " $0}' >&2
  exit 1
fi
echo "::endgroup::"

echo "devcontainer smoke: tiers 1-3 OK"

echo "[devcontainer-smoke][end]"
